01-edu/public

- subjects/printcombn.en.md
Usage program was taken from putnbr sample. `123` cant be called as it is not considered by task description (0 < n < 10). Also, the console output shows putnbr's function call output.
> Fix subject description

- subjects/printnbrinorder.en.md
- subjects/printnbrinorder.fr.md
Instructions missing the condition to sort the digits in ascending order.
> printnbrinorder instructions correction

- subjects/sortintegertable.en.md
No commas on example output as it is required to return []int
> Sortintegertable Task

- subjects/push-swap/push-swap.en.md
1. echo -e "rra\npb\nsa\nrra\npa\n" gives:
rra
pb
sa
rra
pa
_ with one extra line (non needed)
2. ARG="4 67 3 87 23"; ./push_swap "$ARG" | wc -l gives only "6" (without spaces)
> Some examples doesn't work as it shown

- subjects/forum/forum.audit.en.md
According to forum project description, only a use should have only one active session. This should be checked during audit.
> Add unique active session question to forum audit

- go/tests/rc/rc.go
- go/tests/rc/tests/grand-prix-go-burdeux/isnegative.go
- go/tests/rc/tests/moreThanOnePackage/func.go
- go/tests/rc/tests/moreThanOnePackage/main.go
- go/tests/rc/tests/testLiteralRestriction/main.go
Some students have been submitting exercises with the wrong packages: usually mixing packages main and piscine in the same directory which causes a crash in the RC.
I added a verification for the number of packages in the directory and an error message is displayed when more than one package is found.
Since the crash is caused by a mistake in the part of the students and I cannot see a need for the RC to handle more than one package in the same directory this solution serves to avoid the crash of the RC as well as to notify of the reason of the error.
> Avoids that the rc crashes when encountering more than one package in the same directory

- subjects/doop/README.md
- subjects/expandstr/README.md
- subjects/fprime/README.md
- subjects/hiddenp/README.md
- subjects/printbits/README.md
- subjects/printhex/README.md
Minor typos and grammar improvements for READMEs: 
1) doop
2) expandstr
3) fprime
4) hiddenp
5) printbits
6) printhex
> Typos correction and grammar improvements

- subjects/changes/README.md
Link to Rust doc fixed, old link https://doc.rust-lang.org/std/keyword.Self.html is 404.
> Update README.md for changes subject

- subjects/lunch_queue/README.md
`Person.id` was not a valid field. It was supposed to be `Person.discount`.
> Fix `Person` structure in lunch_queue

- subjects/matrix_ops/README.md
The wrong import was used (compared with the expected files).
> docs(matrix_ops): fix import typo

- subjects/roman_numbers_iter/README.md
In usage  `use roman_numbers` changed to `use roman_numbers_iterator` as expected in tests
> Update README.md for roman_numbers_iter

- subjects/ascii/README.md
> docs: Add readme for ascii subject

- subjects/printnbrbase/README.md
The `fmt` package was included but never used in the provided example test program
> Fix unused import

- subjects/ascii-art/justify/audit.md
clarify how parameters should be passed and add escape char to avoid opend double quote
> docs(ascii-art-justify): remove double quotes

- subjects/net-cat/README.md
This issue was pointed out by a student and confirmed by checking in our preview tool.
At the moment it raises two questions:
- Why H2 have `display: none` rule in css
- Why we do add the name of the exercise as `H2` at the start of the subjects
If by any chance you know the answers please let me know
> docs(net-cat): make bonus title visible in the subject

- subjects/ascii-art/color/README.md
- subjects/ascii-art/fs/README.md
- subjects/ascii-art/justify/README.md
- subjects/ascii-art/output/README.md
- subjects/ascii-art/reverse/README.md
- Specify the behavior for programs with multiple optional projects implemented to avoid doubts during audits
- Add clarification on default behaviour - program with only [STRING] argument
> docs(ascii-art-optionals): clarify subjects

- subjects/ascii-art/color/README.md
- subjects/ascii-art/color/audit.md
- subjects/ascii-art/fs/README.md
- subjects/ascii-art/justify/README.md
- subjects/ascii-art/justify/audit.md
- subjects/ascii-art/output/README.md
- subjects/ascii-art/output/audit.md
- subjects/forum/README.md
- subjects/forum/advanced-features/README.md
- subjects/forum/authentication/README.md
- subjects/forum/image-upload/README.md
- subjects/forum/moderation/README.md
- subjects/forum/security/README.md
- subjects/graphql/README.md
- subjects/real-time-forum/README.md
- subjects/real-time-forum/typing-in-progress/README.md
- subjects/social-network/README.md
fix(ascii-art): fixing the way to use the flag on the optional projects
> Issues in public

- subjects/printstr/README.md
There was an extra new line in the description's example.
> DEV-4001 Bring issue from public repo - printstr subject

- subjects/math-skills/README.md
As suggested by user @robcat: 
Spurious references about graphs, x-values, and y-values are removed because they are not connected at all with the subject. The term "statistic population" is introduced, from which it can be inferred that the program should calculate the population variance (and not the sample variance) should fix issue #1618
> DEV-4023 rephrase presentation of the input file

- subjects/ascii-art/color/audit.md
Replace double quotes with single quotes to avoid special char effect
> DEV-4069 improve ascii-art-color audit

- subjects/crossword/README.md
new line in the beginning of output removed as it is not consistent with the audit questions
> Students can get confused by this mistake of putting a new line at the beginning of the output and at the end of input. There is no explanation about it and it seems like a typo as it is inconsistent with the audits as well
> removed the unnecessary empty lines from the string literals
> 2 back tabs were clicked and 2 lines were removed from string literals
> new line in the beginning of output removed

- js/tests/race_test.js
- js/tests/test.mjs
When running the solution you always get the same error `Promise.race is undefined`
Promise.race was set to undefined in the test of the exercise, and because the script that runs the tests uses it it would always show an error. The solution I proposed is to save it in another property and  check  whether Promise.race is undefined when running the tests.
Assuming the reason to set this method to undefined is to avoid 'cheating', other ways this could be implemented could be to obfuscate the name of Promise.race_ to something more meaningless, and perhaps store it outside of  `Promise`.
Another possible way could be to implement the functionality from scratch, but this would be the actual solution for the exercise and it could also  be copied, so it would defeat the purpose of preventing …
> DEV-4309 race bring issue from public

- subjects/ai/keras/README.md
The exercise suggest we use categorical_crossentropy , but the classes in breast cancer data set are actually binary, so binary cross entropy should be used to get the audit answers. 
change the wording from latter to former
> Fix typo in keras (no issue id)

- subjects/make-your-game/audit/README.md
There was an instruction that was making the next instruction confusing, so I added the question that seemed to be missing between both.
> DEV-4412 docs(make-your-game): add missing question

- sh/debian/configure.sh
Currently, the automated deployments rely on the `runner` service to run with the self-hosted docker images (`docker.01-edu.org`). However, recently we implemented GitHub based images in the form of GitHub packages. These packages needs to be retrieved by the `runner` for running newer tests.
Add `runner` v2 support for the configure.sh script. Which includes the deployment capabilities for the `runner` to …
> DEV-4430 Add `runner` v2 support

- subjects/middle_day/README.md
better if `public` and `rust-tests` are merged at the same time.
[Related github issue](https://github.com/01-edu/public/issues/1802)
> DEV 4454 fix-deprecate-method-in-middle-day-rust-piscine

- subjects/atoi-exam/README.md
- subjects/atoibase-exam/README.md
- subjects/capitalize-exam/README.md
- subjects/compare-exam/README.md
- subjects/findprevprime/README.md
- subjects/firstrune-exam/README.md
- subjects/foreach-exam/README.md
- subjects/lastrune-exam/README.md
- subjects/listremoveif-exam/README.md
- subjects/listsize-exam/README.md
- subjects/max-exam/README.md
- subjects/nrune-exam/README.md
- subjects/printcomb-exam/README.md
- subjects/printstr-exam/README.md
- subjects/rot14-exam/README.md
- subjects/slice/README.md
- subjects/sortwordarr-exam/README.md
- subjects/split-exam/README.md
- subjects/strlen-exam/README.md
- subjects/strrev-exam/README.md
- subjects/swap-exam/README.md
DEV-4390
>  Some of the exercises are using the import "piscine" and they need to be removed on the exams.
>  For now, the fix was to create duplicated subjects and new refs for the exercises in the exam, but in the future they will to be removed
> DEV-4390: new readmes for the exams exercises

- js/tests/test.mjs
The reference links returns 404. There is nothing in wayback machine also about the reference link.
I propose if the proposal is rejected, find a working reference link to put.
> Reference link returns 404

- subjects/guess-it-1/README.md
- subjects/guess-it-2/README.md
Github issue: https://github.com/01-edu/public/issues/1870
This impacts two exercises: `guess-it-1` and `guess-it-2`
The `zip` file path has been changed and in it the root dir also have been updated.
> DEV-4717 guess-it-1-js-piscine-fix-inconsistency-in-assets

- subjects/ascii-art/color/audit.md
Tackle [SUP-543](https://01talent.atlassian.net/browse/SUP-543)
The commands tested were not in line whit the expected result described.
- change arguments to test for two audit requests
- minor format change
[SUP-543]: https://01talent.atlassian.net/browse/SUP-543?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV-502 Fix audit requests for `ascii-art color`

- subjects/ai/classification/README.md
- redirect directly to local resources in data directory
> `CON-1749` fix broken URL link in classification readme

- subjects/java/piscine/CleanExtract/README.md
dd messing space in the example result
> fix: add messing space in the example result

- subjects/java/piscine/DoOp/README.md
> fix: fix typo doOp -> DoOp

- subjects/mobile-dev/stock-market/README.md
- subjects/mobile-dev/stock-market/audit/README.md
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/.dockerignore
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/.gitignore
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/.gitignore.old
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/Dockerfile
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/Makefile
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/README.md
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/app.py
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/requirements.txt
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/utils.py
- update the number of stock to be monitored and update frequency to better deal with the API call limits
> CON-1928-improve-stock-market-subject

- subjects/java/piscine/CatInFile/README.md
The missing imports were added, the runner works fine now.
> CON-1980-Fix-issue-2139-CatInFile-exercise-runner-fails

- subjects/system-monitor/README.md
- subjects/system-monitor/audit/README.md
Solve an issue reported by Zone01Rouen
Remove the Power section
Remove the Power section in the subject and audit
> CON-1829-add-missing-information-to-the-system-monitor-project

- subjects/lem-in/README.md
[Github issue](https://github.com/01-edu/public/issues/2173)
> CON-2026-Define-how-many-tunnels-can-connect-two-rooms

- subjects/social-network/README.md
react changed into next.js
[GitHub issue](https://github.com/01-edu/public/issues/2205)
> CON-2110-Replace-react-with-next.js-in-social-network-subject

- subjects/ai/numpy/README.md
- subjects/ai/numpy/audit/README.md
- Make exercise 6 relevant to the topic of broadcasting
> CON-2288 - update `numpy` subejct and audit

- subjects/scan/README.md
- subjects/scan/audit/README.md
Add UTM VMs for mac silicon support, and remove the specification of VirtualBox in the subject and audit
> CON-1866 add VMs for UTM

- subjects/graphql/README.md
- subjects/graphql/audit/README.md
there was no question to verify the usage of the svg as asked in the readme... 
`"This graphs must be done using [SVG]"`
Took the chance to improve the language as well
> CON-2309: graphql improve language

- subjects/ai/keras-2/README.md
- subjects/ai/neural-networks/README.md
fix the virtual env and add better explanation to the subject
> CON-2322: ai branch issues

- subjects/push-swap/audit/README.md
Update audit commands to be in line with the subject to avoid unexpected behaviour from different shell
> CON-2331 update `push-swap` audit commands to run to be in line with subject

- subjects/ai/nlp-spacy/README.md
- subjects/ai/nlp-spacy/audit/README.md
- clarify required goal of exercise.
- update audit question to avoid floating issues.
> CON-2332 update subject and audit of exercise 1 of `nlp-spacy`

- subjects/ai/linear-regression/README.md
fix a  broken link in the radme
> CON-2377 linear-regression

- .github/pull_request_template.md
- .github/workflows/ga-image-build-branch.yml
DEV-5596
Currently, the PRs that are opened by non-01 authors are not being able to be merged due to the lack of permission for external members to build images under our organization's repository. 
> Provide an overview of the solution implemented in this pull request. This should be a high-level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub compliant [`mermaid`](https://mermaid.live/) graphs to visually represent the solution.
We are incorporating a standardized and appropriate pull request template, similar to the rest of our …
> DEV-5596 Improve Public build image on the branch

- subjects/hashing/README.md
- subjects/partial_sums/README.md
This corrects a typing error, as 64 is not a valid type in Rust.
> fix return type of function

- subjects/cybersecurity/active/audit/README.md
- It makes more sense for the flag -p (short for 'ports') to be before the port range
- It makes more sense for the flags -u or -t (short for 'UDP ports' and 'TCP ports') to be either freely placed where-ever or to be placed before the 'ip_address' argument, but not before the port range argument. This mistake happened only inside the audit questions file, it seems to be fine in the task description file.
> Flags are most likely in wrong order for the audit file

- subjects/ascii-art/output/README.md
- substitute " with ' to avoid special symbol interpretation
Addresses the issue raised [here](https://github.com/01-edu/public/pull/1501)
> CON-2477 update-example-command-in 1ascii-art-output`

- subjects/java/piscine/SortArgs/README.md
Restores the default `System.out` to fix result printing
`System.out` was changed to a custom `printStream`, so 
```Java
System.out.println(output.equals("1 2 3 4\n"));
```
printed `true` or `false` to this `printStream` and not the default `System.out`. This caused console output to be empty.
> docs(SortArgs) - Fix bug in ExerciseRunner

- .github/workflows/ga-misc-check-links.yml
Before merging:
- be sure that the new label to skip check is added 
- consider moving the GA to 01-edu
> CON-2526 add new GA to check for broken links

- subjects/shop/README.md
- subjects/shop/audit/README.md
> This change fixes a typo in the README.md file located in the subjects/shop directory. Also the README.md file located in the audit folder within that path. The typo impacts the clarity of the instructions provided in the file.
> The solution involves correcting the typo in the README.md file to ensure that instructions are accurately conveyed to users of the project. This will improve the readability and usability of the documentation.
> The typo was identified in the Instructions section of the README.md file, where the word "adds" was incorrectly used instead of "ads". This change has been made to ensure consistency and clarity throughout the document.
> Fix typo in shop README.md

- subjects/mobile-dev/chess/resources/README.md
> CON-2635 chess broken link

- subjects/canjump/README.md
- subjects/canjump/main.go
CON-2641
canjump new exam exercise
> CON-2641 canjump new exam exercise

- subjects/findpairs/README.md
> CON-2626 new exercise findspairs

- subjects/ascii-art/color/README.md
- subjects/ascii-art/color/audit/README.md
[CON-2716](https://01talent.atlassian.net/browse/CON-2716)
[CON-2716]: https://01talent.atlassian.net/browse/CON-2716?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2716 Fix inconsistency between `ascii-art-color` subject and audit

- subjects/repeatalpha/README.md
- subjects/repeatalpha/main.go
[CON-2671](https://01talent.atlassian.net/browse/CON-2671)
[CON-2671]: https://01talent.atlassian.net/browse/CON-2671?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2672 [CHECKPOINT-RESTRUCTURE] Update `repeatalpha` subject to ask for a function instead of a program

- subjects/java/checkpoints/steady-sequence/ExerciseRunner.java
- subjects/java/checkpoints/steady-sequence/README.md
[CON-2863](https://01talent.atlassian.net/browse/CON-2863)
[CON-2863]: https://01talent.atlassian.net/browse/CON-2863?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2863-Markdown-Steady-Sequence-Exercise

- subjects/java/checkpoints/html-validator/ExerciseRunner.java
- subjects/java/checkpoints/html-validator/README.md
[CON-2881](https://01talent.atlassian.net/browse/CON-2881)
[CON-2881]: https://01talent.atlassian.net/browse/CON-2881?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2881-Markdown-HTML-Validator-Exercise

- subjects/java/checkpoints/breakdown-url/ExerciseRunner.java
- subjects/java/checkpoints/breakdown-url/README.md
[CON-2878](https://01talent.atlassian.net/browse/CON-2878)
[CON-2878]: https://01talent.atlassian.net/browse/CON-2878?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2878-Markdown-Breakdown-URL-Exercise

- subjects/java/checkpoints/harmonious-fusion/ExerciseRunner.java
- subjects/java/checkpoints/harmonious-fusion/README.md
[CON-2830](https://01talent.atlassian.net/browse/CON-2830)
[CON-2830]: https://01talent.atlassian.net/browse/CON-2830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2830 Markdown Harmonious Fusion Exercise

- subjects/java/checkpoints/factorial-master/ExerciseRunner.java
- subjects/java/checkpoints/factorial-master/README.md
[CON-2730](https://01talent.atlassian.net/browse/CON-2730)
[CON-2730]: https://01talent.atlassian.net/browse/CON-2730?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2730 Markdown Factorial Master Exercise

- subjects/java/checkpoints/armstrong-number/ExerciseRunner.java
- subjects/java/checkpoints/armstrong-number/README.md
[CON-2908](https://01talent.atlassian.net/browse/CON-2908)
[CON-2908]: https://01talent.atlassian.net/browse/CON-2908?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2908 Markdown Armstrong Number Exercise

- subjects/DPxAI/embedded-organs/README.md
[CON-2965](https://01talent.atlassian.net/browse/CON-2965)
[CON-2965]: https://01talent.atlassian.net/browse/CON-2965?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2965 Markdown ``DPxAI:Quest00/Ex03``

- subjects/sudoku/audit/README.md
> CON-3020 Update `sudoku` audit

- subjects/DPxAI/declare-everything/README.md
Solving : [CON-3026]('https://01talent.atlassian.net/browse/CON-3026')
[CON-3026]: https://01talent.atlassian.net/browse/CON-3026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3026: Add subject for ``declare-everything``

- subjects/DPxAI/objects-around/README.md
Resolves: [CON-3044](https://01talent.atlassian.net/browse/CON-3044)
[CON-3044]: https://01talent.atlassian.net/browse/CON-3044?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3044 Markdown DPxAI: ``Quest01/objects-around``

- js/tests/objects-around.json
`https://01talent.atlassian.net/browse/CON-3045`
>  -> the two last tests cannot work because the test declare the object called robot and the solution declare it also. So the subject should probably ask to search for name age and hasEnergy in another variable name than robot to avoid conflict.
Fixed
> CON-3045 Tests(DPxAI): Upload test for quest01 objects-around

- dom/first-wink_test.js
[CON-2957](https://01talent.atlassian.net/browse/CON-2957)
I'm not sure how to handle test for dom...
from
`bash ./test_with_container.sh -l dom -s solution.zip first-wink
`
`Building test image based on branch:
[+] Building 8.5s (9/9) FINISHED                                                                               docker:desktop-linux
=> [internal] load .dockerignore                                                                                              0.1s
=> => transferring context: 2B                                                                                                0.0s
=> [internal] load build definition from Dockerfile                                                                           0.1s
=> => transferring dockerfile: 152B …
> CON-2957 Tests(DPxAI): upload test for quest02 first-wink

- dom/colorful-legs_test.js
[CON-3107](https://01talent.atlassian.net/browse/CON-3107)
[CON-3107]: https://01talent.atlassian.net/browse/CON-3107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3107 Tests(DPxAI): upload test for quest02 colorful-legs

- dom/first-hello_test.js
[CON-2962](https://01talent.atlassian.net/browse/CON-2962)
[CON-2962]: https://01talent.atlassian.net/browse/CON-2962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2962 Tests(DPxAI): upload test for quest02 first-hello

- js/tests/glance-on-power.json
- subjects/DPxAI/glance-on-power/README.md
> CON-3161 Fix tests issue for `DP/glance on power"

- subjects/ai/emotions-detector/README.md
- subjects/ai/emotions-detector/audit/README.md
Resolves: CON-3133
- Update train.py to save learning curves and model architecture
- Modify predict.py to evaluate on test set instead of validation set
- Ensure 62% accuracy requirement on test set
> CON-3133 Fix ``AI/emotions detector``

- subjects/AI.GO/first-wink/README.md
- subjects/AI.GO/the-skeleton/README.md
> The instructions were not stating clearly what is expected to be submitted.
- The 'button' element is selected by ID.
- The name of the variables are more expressive.
- The comments in the code example are more compatible with the new solution. Kindly find it in the following PR: [New Solution](https://github.com/01-edu/solutions/pull/92)
- The prompts are compatible with the instructions.
> CON-3184 Fixing instructions in `AI.GO/first-wink`

- js/tests/listed.json
- js/tests/only-if.json
Why?
After the miscine was tested as a student, two tests had some inconsistencies with updated subjects.
Solution Overview
Fixes of inconsistencies to match two updated subjects.
- [only-if ](https://github.com/01-edu/public/tree/master/subjects/AI.GO/only-if)
-  [listed](https://github.com/01-edu/public/tree/master/subjects/AI.GO/listed
)
> DEV-#### Fix of ai.go js tests to match updated subjects

- subjects/AI.GO/only-if/README.md
The instructions were not clarifying enough what will be tested.This goes with tests following the old exercise : special promo.
Added clear instructions that are compatible with the tests.
> CON-3183 Fixing instructions in `AI.GO/only-if`

- .github/workflows/ga-misc-check-compliance.yml
> DEV-6244 Add internal PR compliance checks

- subjects/go-reloaded/README.md
- subjects/wget/README.md
- subjects/wget/audit/README.md
> CON-3263 Fix subjects

- subjects/forum/audit/README.md
> [EXTERNAL] fix audit readme file posts/comments

- subjects/devops/crud-master-py/README.md
DEV-6316
An issue has been reported by a learner regarding the CRUD-Master exercise. The provided schema and file structure show server.js files, but the instructions mention using Python with Flask.
Change the files extensions from js to python in the subject file
> DEV-6316 fix: issue-with-exercise-crud-master-instructions-and-file-structure

- subjects/net-cat/audit/README.md
Remove confusing quotes:
- "./TCPChat"
- "./TCPChat" 2525 localhost
- "./TCPChat 2525"
The first two commands are correct, but the third one will result in the error message `no such file or directory`. This happens because the shell interprets it as referring to a file literally named `"./TCPChat 2525`". The second and third commands are conflicting, enclosing both the executable name and its argument in a single set of quotes is not valid. For reference, please consult the [audit file](https://github.com/sadiqui/public/tree/master/subjects/push-swap/audit) of the push-swap project, where quotes are used only to ensure that an entire sequence is treated as a single argument.
> [EXTERNAL] Project `net-cat`: Remove confusing quotes

- js/tests/elementary_test.js
- subjects/elementary/README.md
DEV-#### | SUP-#### | CON-####
The question can be skipped using eval
```js
function multiply(n1, n2) {
return eval(`${n1} ${String.fromCharCode(42)} ${n2}`)
}
function divide(n1, n2) {
return eval(`Math.trunc(${n1} ${String.fromCharCode(47)} ${n2})`)
}
function modulo(n1, n2) {
return eval(`Math.trunc(${n1} ${String.fromCharCode(37)} ${n2})`)
}
```
> Provide an overview of the solution implemented in this pull request. This should be a high-level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub-compliant …
> [EXTERNAL] undefine eval() for elementary.js

- subjects/cybersecurity/hole-in-bin/README.md
every exercise can currently be solved by using strings for example
` strings bin | grep "modified"` 
to give the message required to complete the exercise.
However, that technique will teach us nothing about binary inspection, reverse engineering or binary manipulation.
DEV-#### | SUP-#### | CON-####
> It is important to learn concepts, not circumvent the exercise.
> Explicitly forbid strings command
> Added one line to README
> Please assign the label `📦 build` If you want to re-build the following test images:
>- `💻 Sh` 
>- `🚀 JS`
>- `🧩 DOM`
> [EXTERNAL] add strings to forbidden

- subjects/pick-omit/README.md
I have added the condition that was not included in the task description but was included in the tests. also __proto__ is  a non standard property.
It maybe good to mention as the first test usually fails just because it is not mentioned to ignore the properties from the prototype chain.
> Impovement in task description needed
> [EXTERNAL] Condition in tests but not in task description

- js/tests/happiness-manager_test.mjs
- js/tests/level-up.json
- subjects/happiness-manager/README.md
- subjects/level-up/README.md
[CON-1035](https://01talent.atlassian.net/browse/CON-1035)
- I removed all the references that I could find in public.
- I had to modify slightly the descriptions.
- I also took the chance to fix the typos on the readmes that were modified.
- I left the wine exercise on the ai branch as all the exercise depends on a wine dataset, not sure how that could be replaced.
[CON-1035]: https://01talent.atlassian.net/browse/CON-1035?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-1035 Remove alcohol terminology

- dom/class-it_test.js
[CON-3221](https://01talent.atlassian.net/browse/CON-3221)
[CON-3221]: https://01talent.atlassian.net/browse/CON-3221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3221 Fix the class-it test so it accepts reverted order of classes

- subjects/roman_numbers/README.md
> The expected functions and Usage of the `roman_numbers` task of the `traits` quest has a conflicting implementation of traits, aka duplicate usage of the `debug` trait, which leads to compilation error. This PR removes this conflict/duplication of traits.
> The solution only removes the duplicate trait from the readme, to remove the duplication and avoid the compilation error.
> fix(rust-roman_numbers): remove conflicting traits from expected data structure

- subjects/is_anagram/README.md
- subjects/strings/README.md
These subjects are deemed necessary for this branch for now so things don't break. From now on changes will be applied on a new branch.
> fix(rust-quest03): re-added removed subjects

- subjects/forum/audit/README.md
Fixes typos and improves grammar in the Docker-related instructions of the audit file.
> [EXTERNAL] `forum` Fix typos and some grammar

- subjects/devops/deep-in-system/README.md
- subjects/devops/deep-in-system/audit/README.md
CON-3314
Resolves #2543
Improve the audit quality for macOS users
> CON-3314 Improve `deep-in-system` audit for macOS students

- subjects/forum/README.md
- subjects/forum/authentication/README.md
- subjects/forum/security/README.md
- subjects/real-time-forum/README.md
- subjects/social-network/README.md
In `social-network` I replaced the [allaboutcookies - sessions](https://allaboutcookies.org/what-are-session-cookies) link with [cheatsheetseries.owasp - sessions](https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html#session-management-waf-protections), as the former lacks depth and is ad-heavy. The new resource provides comprehensive guidance on web session management, including session ID handling, secure cookies, storage APIs, attack prevention, and monitoring.
I also added this link, along with [developer.mozilla - cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) to the previous projects `forum` and `real-time-forum` where they are most needed.
> [EXTERNAL] Add links to valuable resource: `forum`, `real-time-forum`, `social-network` 

- subjects/cybersecurity/hole-in-bin/README.md
DEV-6587
changing the hash of the vm to make it match the vm.
> DEV-6587: Cybersecurity hole in bin SHA1 don't match

- subjects/more-or-less/README.md
Aligns the exercise instructions with the existing tests by clarifying that `more` and `less` must take exactly one argument, while `add` and `sub` must take exactly two. This ensures students write functions that pass [the enforced tests](https://github.com/01-edu/public/blob/ebcc577daeafd50ab057493e13e173767257a97d/js/tests/more-or-less_test.js) of arguments in functions signatures:  
- `t(() => more.length === 1)`  
- `t(() => less.length === 1)`  
- `t(() => add.length === 2)`  
- `t(() => sub.length === 2)`  
Related PR: [#2882](https://github.com/01-edu/public/pull/2882)
The tests are correct; it's the instructions that needed to be clearer to better align with them.
> [EXTERNAL] `more-or-less` Align with the exercise's test

- subjects/forum/security/audit.md
- subjects/forum/security/audit/README.md
The requirement was to check whether the session cookie contains a UUID:
https://github.com/01-edu/public/blob/ebcc577daeafd50ab057493e13e173767257a97d/subjects/forum/security/audit/README.md?plain=1#L21
If this condition is met, then UUIDs are already implemented in session management:
https://github.com/01-edu/public/blob/ebcc577daeafd50ab057493e13e173767257a97d/subjects/forum/security/audit/README.md?plain=1#L33
Therefore, this second "bonus" question about UUID implementation was removed, as it would always be redundant when the requirement is satisfied.
> [EXTERNAL] `forum-security` Remove redundant question

- subjects/make-your-game/score-handling/README.md
The [Gorilla WebSocket](https://pkg.go.dev/github.com/gorilla/websocket) package is not needed for this project. WebSockets are typically used for real-time bidirectional communication, such as live chat or multiplayer games. However, since only one player interacts with the game at a time, WebSockets are unnecessary.
For this project, a Go API service using HTTP endpoints is sufficient to handle the scoreboard. The player’s score will be sent via a POST request, and the server will store it in a JSON file. A GET request will retrieve the stored scores when needed. This is explicitly stated in the project instructions:
https://github.com/01-edu/public/blob/ebcc577daeafd50ab057493e13e173767257a97d/subjects/make-your-game/score-handling/README.md?plain=1#L7-L11
The implementation will rely …
> [EXTERNAL] `make-your-game:score-handling` WebSocket package is not needed

- subjects/ascii-art-web/dockerize/audit/README.md
Replace with results that closely resemble the anticipated or desired outputs.
Example:
container's name: postgres -> dockerize
> [EXTERNAL] `ascii-art-web-dockerize` Mimic expected outputs

- subjects/net-cat/audit/README.md
Remove confusing quotes:
- "./TCPChat"
- "./TCPChat" 2525 localhost
- "./TCPChat 2525"
The first two commands are correct, but the third one will result in the error message `no such file or directory`. This happens because the shell interprets it as referring to a file literally named `"./TCPChat 2525`". The second and third commands are conflicting, enclosing both the executable name and its argument in a single set of quotes is not valid. For reference, please consult the [audit file](https://github.com/sadiqui/public/tree/master/subjects/push-swap/audit) of the push-swap project, where quotes are used only to ensure that an entire sequence is treated as a single argument.
PS: This issue was previously fixed in this [merged pull request …
> [EXTERNAL] fix(`net-cat`): remove confusing quotes

- subjects/mini-framework/README.md
- subjects/mini-framework/audit/README.md
Fix minor documentation issues: standardized the "Routing System" header format, corrected a typo ("auditers" → "auditors"), and updated the TodoMVC example link to a valid one.
> [EXTERNAL] docs(`mini-framework`): fix subject and audit file

- subjects/matrix_transposition/README.md
Previously, URLs used the `highlight=` parameter to emphasize specific sentences in shared documentation links. However, this approach highlighted every individual occurrence of each word, rather than treating phrases as a single unit, leading to cluttered and imprecise highlights on the page.
This PR replaces the `highlight=` parameter with the `#:~:text=` fragment syntax, enabling exact phrase-level highlighting in supported browsers (Chrome, Edge, and others), while keeping source URLs the same.
> [EXTERNAL] docs(`matrix-transposition`): precise title highlighting in notions links

- subjects/modify_letter/README.md
output section the first out put should be "John" instead of "Joe"
> Before starting, please choose the relevant pull request **Labels**, **Reviewers**, and **Assignees** </br>
> Here are a couple of example tiles of a good pull request:
> - `CON-1234 Title of The Feature or Fix`
> - `[EXTERNAL] Title of The Feature or Fix`
CON-#### | [EXTERNAL]
> Provide an overview of the solution implemented in this pull request. This should be a high-level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub-compliant [`mermaid`](https://mermaid.live/) graphs to represent the solution visually.
> Explain the details of the implementation and the …
> [EXTERNAL] docs(modify-letter): Changed to the correct output

- subjects/box_recursion/README.md
**1.** Make it clear, that student should complete this type alias, guided by instructions:
```
Additionally, create a type named Link, which will be the connection between the WorkEnvironment and Worker structures. It will point to None if there is no Worker to point to.
```
```diff
- pub type Link;
+ pub type Link = _; // Complete type alias
```
**2.** role field of Worker structure, is expected to be of type Role. Tests Need It as checks expect "Role::CEO, not "CEO".
```diff
- pub role: String,
+ pub role: Role,
```
----
Related files:
- Tests: https://github.com/01-edu/rust-tests/blob/master/tests/box_recursion_test/src/lib.rs
- Solution: https://github.com/01-edu/rust-tests/blob/master/solutions/box_recursion/src/lib.rs
> [EXTERNAL] fix(`box_recursion`): fix expected code

- subjects/ai/keras-2/README.md
Solution Overview
This pull request addresses a documentation typo in the README.md file.
The word “no” was mistakenly used instead of “not”, which could lead to confusion for readers.
The solution implemented is straightforward:
Corrected “no” → “not” in the affected sentence.
Corrected “go” → “goal” in the affected sentence.
No additional modifications were made to the surrounding content.
This ensures the documentation is clearer and more accurate for users referencing it.
> [EXTERNAL] fix(keras-2): correct typo in README (no → not and go → goal)

- subjects/ai/keras-2/README.md
- subjects/previousprime/README.md
- subjects/previousprime/main.rs
Docs-only fix in **Keras 2 → Exercise 4 (Multi-class classification – Optimize)**:
Replace the incorrect mention of `binary_crossentropy` with the correct `categorical_crossentropy` for **single-label multi-class** classification.
`binary_crossentropy` is intended for **binary** or **multi-label** tasks.
For **single-label multi-class** with a softmax output, the appropriate loss is **`categorical_crossentropy`**. This correction prevents learner confusion and aligns the subject with standard Keras practice.
* **Updated text** in Exercise 4 to say `categorical_crossentropy` instead of `binary_crossentropy`.
> [EXTERNAL] docs(keras2): use categorical_crossentropy for single-label multi-class

- subjects/chaikin/README.md
- **Updated** the Chaikin's Algorithm link to a working PDF version hosted by UNC.
- From: http://graphics.cs.ucdavis.edu/education/CAGDNotes/Chaikins-Algorithm/Chaikins-Algorithm.html
- To: https://www.cs.unc.edu/~dm/UNC/COMP258/LECTURES/Chaikins-Algorithm.pdf
- **Fixed** a grammar redundancy: "only has only" → "has only".
> [EXTERNAL] fix(`chaikin`): update broken link + grammar correction

- subjects/ai/credit-scoring/README.md
> [EXTERNAL] docs (credit-scoring): fix and update resource links in documentation

- subjects/ai/matrix-factorization/README.md
> [EXTERNAL] docs (matrix-factorization): fix and update resource links in documentation

- subjects/ai/sp500-strategies/README.md
> [EXTERNAL] docs (sp500): fix and update resource links in documentation
