01-edu/public

- docs/modular-steps-management.md
- add countries input type
- change subtype names
- enhance form step example
> Maj doc steps

- subjects/doop.en.md
Added details and corrected unclearness
> Update of doop

- subjects/boolean.en.md
- subjects/boolean.fr.md
- subjects/cat.en.md
- subjects/cat.fr.md
- subjects/displayfile.en.md
- subjects/displayfile.fr.md
- subjects/point.en.md
- subjects/point.fr.md
- subjects/ztail.en.md
- subjects/ztail.fr.md
Translations and review of exercices for quest 08.
> Quest8review translations

- subjects/comcheck.en.md
- subjects/comcheck.fr.md
Chris its missing the french part
> fixed the comcheck readme but need to translate to fr

- subjects/enigma.en.md
- subjects/enigma.fr.md
> fixing readme enigma exercise from hackathon

- subjects/eightqueens.en.md
- subjects/eightqueens.fr.md
- subjects/fibonacci.en.md
- subjects/fibonacci.fr.md
- subjects/findnextprime.en.md
- subjects/findnextprime.fr.md
- subjects/isprime.en.md
- subjects/isprime.fr.md
- subjects/iterativefactorial.en.md
- subjects/iterativefactorial.fr.md
- subjects/iterativepower.en.md
- subjects/iterativepower.fr.md
- subjects/recursivefactorial.en.md
- subjects/recursivefactorial.fr.md
- subjects/recursivepower.en.md
- subjects/recursivepower.fr.md
- subjects/sqrt.en.md
- subjects/sqrt.fr.md
Missed character in the word instructions:)
> fixed instructions typo

- subjects/fibonacci.en.md
- subjects/fibonacci.fr.md
- subjects/findnextprime.en.md
- subjects/findnextprime.fr.md
- subjects/isprime.en.md
- subjects/isprime.fr.md
- subjects/iterativefactorial.en.md
- subjects/iterativefactorial.fr.md
- subjects/iterativepower.en.md
- subjects/iterativepower.fr.md
- subjects/recursivefactorial.en.md
- subjects/recursivefactorial.fr.md
- subjects/recursivepower.en.md
- subjects/recursivepower.fr.md
- subjects/sqrt.en.md
- subjects/sqrt.fr.md
Fixed a typo in the functions input order.
> fixed tasks input

- subjects/rot14.en.md
On exam not all students faced rot13 before.
> Clarify rot14

- subjects/printcombn.en.md
If you passing parameter with '2' it should have output like these 
01, 02, 03, 04, 05, 06, 07, ... 67, 78, 89
OR 
you just have to simply replace 3 by 2
> Little fix

- subjects/balancedstring.en.md
- subjects/nauuo.en.md
Subjects balancedstring and nauuo added for team alem final exam and training purposes
> addition of balancedstring and nauuo subjects

- subjects/ascii-art/ascii-art-output.audit.en.md
432 in result, but 32 in argument
> wrong argument

- subjects/ascii-art/ascii-art-output.audit.en.md
23 in argument, but 123 in result
> wrong argument 2

- subjects/groupie-tracker/groupie-tracker-geolocalization.audit.en.md
https://groupietrackers.herokuapp.com/api/locations/42
> fixing city name

- subjects/groupie-tracker/groupie-tracker-geolocalization.audit.en.md
https://groupietrackers.herokuapp.com/api/artists/23
https://groupietrackers.herokuapp.com/api/locations/23
> fixing wrong artist name and city

- subjects/groupie-tracker/groupie-tracker-geolocalization.audit.en.md
http://groupietrackers.herokuapp.com/api/artists/1
https://groupietrackers.herokuapp.com/api/locations/1
> adding one missed location

- subjects/printchessboard.en.md
Added 0, 0 case. I thought it should print "" and lost xp(
> Added new case

- subjects/tetris-optimizer/badexample00.md
- subjects/tetris-optimizer/badexample01.md
- subjects/tetris-optimizer/badexample02.md
- subjects/tetris-optimizer/badexample03.md
- subjects/tetris-optimizer/badexample04.md
- subjects/tetris-optimizer/goodexample00.md
- subjects/tetris-optimizer/goodexample01.md
- subjects/tetris-optimizer/goodexample02.md
- subjects/tetris-optimizer/goodexample03.md
- subjects/tetris-optimizer/tetris-optimizer.audit.en.md
What I updated:
- Headers with numeric sequence in examples (good, bad and hard examples).
- Links in audit. Now it's more presentable.
`Changed files in subjects/tetris-optimizer/...`
> update tetris-optimizer audit and examples

- subjects/sums.en.md
Test checks array structure.
The task description doesn't gives the right way to do it well without "oh snap!")
> Testing in that way

- subjects/dr-strange.en.md
Its unknown from which date week number should be count.
> Update addWeek description

- subjects/has-city/README.md
It is not clarified what should be returned
> Fix has_city subject text

- subjects/flow/README.md
It took me 10 min to realize why I can't execute the code xD
> Fix code in flow

- subjects/build-brick-and-break/README.md
One of the links was in french. Changed to english.
> Update build-brick-and-break subject

- dom/keycodes-symphony_test.js
Handle only alphabet letters like specified in the instructions.
> Fixed the test

- subjects/pick-and-click/README.md
- subjects/pick-and-click/index.html
Made the instructions more precise + removed optional css classes
> Updated pick and click

- subjects/curry-entries/README.md
Add clarifications on function parameters and function description.
> Update README.md of curry-entries

- subjects/flagger/README.md
> Update README.md of flagger

- subjects/neuron/README.md
"questions" instead "question"
> neuron mistype

- subjects/debounce/README.md
> Update README.md of debounce

- subjects/keep-trying-or-giveup/README.md
> Update README.md, clarify keep-trying-or-giveup

- subjects/is-winner/README.md
> Update README.md is-winner, fix display

- subjects/interpolation/README.md
Add clarification that interpolation point should be calculated within interval
> Update README.md interpolation

- subjects/race/README.md
> Update README.md race.js

- subjects/series/README.md
> Update README.md of series

- subjects/make-your-game/README.md
What I changed:
- Links to eng-lang version
> make-your-game

- subjects/throttle/README.md
> Update README.md, add link css-tricks#throttle

- subjects/abort/README.md
fixing of subject abort. (chris'mistake)
> restoring erased subject 'abort'

- rust/tests/changes_test/src/main.rs
- subjects/changes/README.md
I didn't like the exercise `changes` so I change it completely
> Improve exercise `changes`

- subjects/division_and_remainder/README.md
- subjects/fibonacci2/README.md
- subjects/find_factorial/README.md
- subjects/groceries/README.md
- subjects/hello_rust/README.md
- subjects/looping/README.md
- subjects/matrix_transposition/README.md
- subjects/reverse_string/README.md
- subjects/scalar/README.md
- subjects/speed_transformation/README.md
- subjects/temperature_conv/README.md
- subjects/tuples/README.md
@augusto-mantilla 
All subjects are reviewed except Looping (program) not working. I will do it as soon as the test is fixed. 
I reformatted, added a few links in Notions.
I corrected all mistakes in the Usage programs. (missing use import, missing pub in exepected functions)
(I hope those were not intentional, if it was, sorry)
New order proposed
reverse_string after find_factorial
division_and_remainder
tuples
matrix_transposition last
the rest is good in my opinion. :)
Cool stuff. 
Also from now on if I believe a test is broken I will consult you directly to not waste time.
> Rust subject review quest 01

- subjects/brackets_matching/README.md
- subjects/inv_pyramid/README.md
- subjects/road_intersection/README.md
- subjects/road_intersection/audit/README.md
- subjects/scytale_cipher/README.md
- subject and audit for rust raid 02
- contains some subjects for rust exercises
> road_intersection: rust s raid 2

- subjects/fibonacci2/README.md
due to import errors, the function should be public
> make the function public

- subjects/arrange_it/README.md
- subjects/arrays/README.md
- subjects/bigger/README.md
- subjects/borrow/README.md
- subjects/borrow_me_the_reference/README.md
- subjects/capitalizing/README.md
- subjects/card_deck/README.md
- subjects/changes/README.md
- subjects/circle/README.md
- subjects/collect/README.md
- subjects/copy/README.md
- subjects/edit_distance/README.md
- subjects/hashing/README.md
- subjects/looping/README.md
- subjects/name_initials/README.md
- subjects/ownership/README.md
- subjects/simple_hash/README.md
- subjects/string_literals/README.md
- subjects/string_permutation/README.md
- subjects/strings/README.md
- subjects/tic_tac_toe/README.md
- subjects/to_url/README.md
```console Caused by:
failed to load source for dependency `rand`
Caused by:
Unable to update registry `https://github.com/rust-lang/crates.io-index`
Caused by:
failed to fetch `https://github.com/rust-lang/crates.io-index`
Caused by:
network failure seems to have happened
if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli
Caused by:
failed to resolve address for github.com: Temporary failure in name resolution; class=Net (12)```
```console
Issue with the test: char_lenght instead of char_length
```
console ```
error: failed to get `collect` as a dependency of package `collect_test v0.1.0 (/jail/tests/collect_test)` Caused by: failed to load source for dependency `collect` Caused by: Unable …
```
> Rust subject review quest 03

- subjects/banner/README.md
- subjects/boxing_todo/README.md
- subjects/cipher/README.md
- subjects/does_it_fit/README.md
- subjects/error_types/README.md
- subjects/expected_variable/README.md
- subjects/handling/README.md
- subjects/macro_calculator/README.md
- subjects/middle_day/README.md
- subjects/mobs/README.md
- subjects/panic/README.md
- subjects/profanity_filter/README.md
- subjects/question_mark/README.md
- subjects/shopping_mall/README.md
- subjects/unwrap_or_expect/README.md
- middle_day
There was no section expected function but I guessed it was because the student has to find out the signature of the function.
I added one section
Expected Function 
With the message: 
For this exercise the signature of the function has to be found out.
- does_it_fit
I do not think that the person who wrote this one realized that the title of this exercise has a sexual innuendo. ( showed it to clem, it s not just me who saw it right away :) )
It needs to be changed to something else. 
Maybe call it 
areas_volumes_fit   or area_volumes_fitter
Whichever is chosen,
Let’s not forget to change it in the title of the readme and the import in the usage program. 
Also I added the module areas_volumes to the subject ( it said will be given).
- Macro_calculator
Error when testing with …
> Rust subject review quest 05

- subjects/blood_types/README.md
- subjects/border_cross/README.md
- subjects/commits_stats/README.md
- subjects/delete_prefix/README.md
- subjects/events/README.md
- subjects/generics/README.md
- subjects/lalgebra_scalar/README.md
- subjects/lalgebra_vector/README.md
- subjects/lifetimes/README.md
- subjects/matrix/README.md
- subjects/matrix_ops/README.md
- subjects/roman_numbers/README.md
- subjects/roman_numbers_iter/README.md
- subjects/traits/README.md
- subjects/vector_operations/README.md
- Traits, 
Unclear,
"Define both structures fruits and meat", 
The structures are already defined in the subject
Maybe say "Define the impl food for fruit and for meat" 
Additionally
Fruits increases strength by 1 unit
Meat increases strength by 3 units
In the example given 
Player eats an apple and gets  strength increase by 4
Eats a steak and gets strength increased by 9
The solution give the food weight in kg multiplied by 4
There is a lack of information about the formula. This exercise is not achievable as it is. It needs clarifications.
Morevoer,
"Define the std::fmt::Display trait of the Player structure so using
// the template {} inside a println! macro will print in the first
// line the name of the player
// in the second line the strength, score and the money
// and in the …
> first pass remarks

- subjects/borrow_box/README.md
- subjects/box_it/README.md
- subjects/box_recursion/README.md
- subjects/drop_the_thread/README.md
- subjects/how_many_references/README.md
- subjects/ref_cell/README.md
- No major changes on those exercises. 
- All tests are passing. 
- Did a few typo and formatting updates.
> first pass

- subjects/happiness-manager/README.md
- subjects/personal-shopper/README.md
- subjects/tell-me-who/README.md
little updates on subjects after feedback from students and team
> Node quest updates

- subjects/adding/README.md
- subjects/adding_twice/README.md
- subjects/closures/README.md
- subjects/get_products/README.md
- subjects/highest/README.md
- subjects/iterators/README.md
- subjects/project_motion/README.md
- subjects/sales/README.md
- subjects/slices_to_map/README.md
- subjects/step_iterator/README.md
- Highest 
Issue with the usage test
```console
10 |     let n = Numbers::new(&expected);
|                      ^^^ function or associated item not found in `Numbers<'_>`
In the subject it is said that the struct numbers is provided
```
Are they supposed to code the new function as well and complete the usage?
Or is it just forgotten in the usage?
- Iterators
Same issue issue than with highest
Same questions
- Slices to map 
Corrected the output of the example of usage, 
(the order of keys was in the wrong order)
However, if the order of the keys did matter (in the display), check that I did use the usage correctly. 
- Project motion
Access denied with link of the [projectile motion](https://cimg2.ck12.org/datastreams/f-d%3Abb024be6673110b31e78b46819e792adaed8dc661e082a61f0a6d64e%2BIMAGE% …
> first pass on quest 08

- subjects/diamond_creation/README.md
- subjects/logic_number/README.md
- subjects/ordinal/README.md
- subjects/pangram/README.md
- subjects/pig_latin/README.md
- subjects/rgb_match/README.md
- subjects/rot/README.md
- subjects/scores/README.md
- subjects/searching/README.md
- subjects/spelling/README.md
- subjects/stars/README.md
- subjects/talking/README.md
- searching
The instructions do not address what happens if there are identicals keys in the array.
Example: 
let ar = [6,6,6,6,6,6];
let f = search(&ar, 6);
The answer is 
Some(3) when testing with the official solution. 
Edit: I checked the tests and there is never twice the same key but I think this case should be addressed in the subject.
At first I thought it was a classical “find” function (with another name) wich would return the first one encountered. (0)
I added the sentence,
`Only arrays with uniques keys will be tested.`
To make this subject more precise. Double check if I did not change the nature of the intended exercise. 
- spelling
I added that only positive numbers and numbers up to 1 million would be tested.
I noticed that there is no implementation of random numbers in …
> first pass quest 09 rust

- subjects/stock-exchange-sim/examples/seller/seller.log
All processes that could be done  in the same time, should be done in parallel , to provide most efficient solution, here is example
> Wrong example

- subjects/alphacount/README.md
- subjects/atoibase/README.md
- subjects/basicjoin/README.md
- subjects/capitalize/README.md
- subjects/compare/README.md
- subjects/firstrune/README.md
- subjects/index/README.md
- subjects/isalpha/README.md
- subjects/isnumeric/README.md
- subjects/isprintable/README.md
- subjects/join/README.md
- subjects/lastrune/README.md
- subjects/nrune/README.md
- subjects/printnbrbase/README.md
- subjects/printnbrinorder/README.md
- subjects/tolower/README.md
- subjects/toupper/README.md
- subjects/trimatoi/README.md
1. adding of resources :
- `basicatoi` added `[string concatenation](https://golang.org/ref/spec#Arithmetic_operators)`
- `compare` added `[strings/Compare](https://golang.org/pkg/strings/#Compare)`
- `firstrune`, `lastrune` and `nrune` added `[rune-literals](https://golang.org/ref/spec#Rune_literals)`
- `index` added `[strings/Index](https://golang.org/pkg/strings/#Index)`
- `join` added `[strings/Join](https://golang.org/pkg/strings/#Join)` and changed the subject
- `printnbrbase` added `[01-edu/z01](https://github.com/01-edu/z01)`
- `tolower` added `[strings/ToLower](https://golang.org/pkg/strings/#ToLower)`
- `toupper` added `[strings/ToUpper](https://golang.org/pkg/strings/#ToUpper)`
- `printnbrinorder` added ` [01-edu/z01](https://github.com/01-edu/z01)`and …
> test and resources check quest 05

- subjects/advancedsortwordarr/README.md
- subjects/any/README.md
- subjects/countif/README.md
- subjects/doop/README.md
- subjects/foreach/README.md
- subjects/issorted/README.md
- subjects/map/README.md
1. adding of resources :
for every exercise that uses functions passed as parameters :
- `[Function literals](https://golang.org/ref/spec#Function_literals)`
- `[Function declaration](https://golang.org/ref/spec#Function_declarations)`
- `[Function types](https://golang.org/ref/spec#Function_types)`
other exercises from the quest 05 did not need resources, videos already explain the basics.
2. tests:
- all go tests where tested using the platform and locally
exercises that use functions as parameters where not clear, because the student didn't know what functions are being used to test <https://github.com/01-edu/go-tests/pull/3>
> test and resources check quest 09

- subjects/fibonacci2/README.md
- subjects/hello-there/README.md
- subjects/how-2-js/README.md
- subjects/introduction/README.md
Added this text: 
```
Videos designed to give **hints** are assigned to each quest. It is strongly suggested to watch them as you go.
```
To all first exercises of each piscine: 
- `introduction` *(Piscine Go)*
- `how-2-js` *(Piscine JS)*
- `hello-there` *(Discovery piscine)*
- `fibonacci2` *(Piscine RUST)*
> added video hint to each first exercise of piscine

- subjects/half-a-million/README.md
Fix variable name in the subject
> Update half-a-million README.md

- subjects/ispowerof2/README.md
- subjects/max/README.md
- subjects/rot13/README.md
- subjects/rot14/README.md
- subjects/searchreplace/README.md
- subjects/wdmatch/README.md
Small improvement:
Grammatical clarifications.
Adding of some examples in some cases to match the tests.
> Clarifications and typos

- subjects/chunk/README.md
- subjects/foldint/README.md
- subjects/grouping/README.md
- subjects/itoabase/README.md
- subjects/piglatin/README.md
- subjects/reduceint/README.md
- subjects/revwstr/README.md
- subjects/romannumbers/README.md
- subjects/slice/README.md
- subjects/union/README.md
1) Typos and clarification
2) Correction of Roman numbers example that will require a change of the solution in the test.
> Clarifications and typos3

- subjects/guess-it-1/README.md
- subjects/guess-it-1/audit/README.md
- subjects/guess-it-2/README.md
- subjects/guess-it-2/audit/README.md
- subjects/linear-stats/README.md
- subjects/linear-stats/audit/README.md
- subjects/make-it-better/README.md
- subjects/math-skills/README.md
- subjects/math-skills/audit/README.md
This PR contains the READMEs and the audits of the new projects requested by Nicolas.
It consists of 4 projects in which the math knowledge of the students will be put to the test. These projects focus on statistical calculations, like the average, standard deviation, linear regression line, etc.
The first project focus on the calculation of the average, median, standard deviation and variance of a set of data. Similarly the third exercise consists on the calculation of the linear regression line and the Pearson's correlation coefficient. The second and fourth projects consist on the usage of the previous calculus to guess a next number of a sequence of numbers.
> 1st Stats Projects

- subjects/forum/advanced-features/README.md
- subjects/forum/authentication/README.md
- subjects/forum/image-upload/README.md
- subjects/forum/moderation/README.md
- subjects/real-time-forum/README.md
- subjects/real-time-forum/typing-in-progress/README.md
added missing allowed packages for forum optionals, real-time-forum and real-time-forum typing-in-progress;
moved allowed packages section to the end of readme file in forum moderation, like in other readme files
> add missing allowed packages

- subjects/maxwordcountn/README.md
Tested  and written with @Frenchris
> Add new subject for the map exercice in the piscine

- subjects/ascii-art/README.md
- subjects/ascii-art/color/README.md
- subjects/ascii-art/fs/README.md
- subjects/ascii-art/justify/README.md
- subjects/ascii-art/output/README.md
- subjects/ascii-art/reverse/README.md
- subjects/forum/README.md
- subjects/forum/advanced-features/README.md
- subjects/forum/audit/README.md
- subjects/forum/image-upload/README.md
- subjects/forum/moderation/README.md
- subjects/forum/security/README.md
- subjects/go-reloaded/README.md
- subjects/groupie-tracker/README.md
- subjects/groupie-tracker/filters/README.md
- subjects/groupie-tracker/geolocalization/README.md
- subjects/lem-in/README.md
- subjects/my-ls-1/README.md
- subjects/net-cat/README.md
- subjects/push-swap/README.md
- subjects/tetris-optimizer/README.md
issue https://github.com/01-edu/public/issues/905
> forum/security : issue correction

- subjects/ascii-art-web/export-file/README.md
- subjects/ascii-art-web/stylize/audit.md
- subjects/groupie-tracker/README.md
- subjects/groupie-tracker/audit/README.md
> taking care of issue in public regarding testing in the project

- subjects/has-city/README.md
> has-city: Specify type of paramaters/return values

- subjects/make-your-game/different-maps/README.md
Fix typos
Improve grammar, and clarity
> Update README.md for make-your-game-different-maps

- subjects/make-your-game/history/README.md
Fix typos
Improve grammar, and clarity
> Update README.md for make-your-game-history

- subjects/make-your-game/README.md
Fix typos
Improve grammar, and clarity
> Update README.md for make-your-game

- subjects/go-reloaded/README.md
changed a spelling mistake and changed a few sentences to make the project easier to read.
> Update README.md for go-reloaded subject

- docs/piscine-rust-curriculum.md
Change hyphen to underscore
Fix typo "perfix" into "prefix"
> Fix the broken links

- subjects/abs/README.md
- subjects/biggie-smalls/README.md
- subjects/block-chain/README.md
- subjects/change/README.md
- subjects/circular/README.md
- subjects/collections/README.md
- subjects/concat-str/README.md
- subjects/declarations/README.md
- subjects/dog-years/README.md
- subjects/how-2-js/README.md
- subjects/is/README.md
- subjects/last-first-kiss/README.md
- subjects/method-man/README.md
- subjects/min-max/README.md
- subjects/more-or-less/README.md
- subjects/mutability/README.md
- subjects/physics/README.md
- subjects/primitives/README.md
- subjects/returns/README.md
- subjects/sign/README.md
Grammar review of the language in the first JavaScript quest.
> Review language piscine jsdata quest c 2

- subjects/division_and_remainder/README.md
- subjects/fibonacci2/README.md
- subjects/find_factorial/README.md
- subjects/groceries/README.md
- subjects/looping/README.md
- subjects/matrix_transposition/README.md
- subjects/reverse_string/README.md
- subjects/scalar/README.md
- subjects/speed_transformation/README.md
- subjects/temperature_conv/README.md
- subjects/tuples/README.md
Language review of the first rust quest.
> 0 review language piscine rustquest 01 c 360

- subjects/arrange_it/README.md
- subjects/borrow/README.md
- subjects/borrow_me_the_reference/README.md
- subjects/copy/README.md
- subjects/doubtful/README.md
- subjects/name_initials/README.md
- subjects/ownership/README.md
- subjects/string_literals/README.md
- subjects/tic_tac_toe/README.md
- subjects/to_url/README.md
Language review of the second rust piscine.
> 1 review language piscine rustquest 02 c 461

- subjects/arrays/README.md
- subjects/bigger/README.md
- subjects/capitalizing/README.md
- subjects/card_deck/README.md
- subjects/changes/README.md
- subjects/circle/README.md
- subjects/collect/README.md
- subjects/edit_distance/README.md
- subjects/hashing/README.md
- subjects/simple_hash/README.md
- subjects/string_permutation/README.md
- subjects/strings/README.md
A language review of the third rust piscine quest.
> 2 review language piscine rustquest 03 c 398

- subjects/drawing/README.md
Language review of the first rust raid.
> 4 review language piscine rustdrawing c 446

- subjects/counting_words/README.md
- subjects/insertion_sort/README.md
- subjects/inv_pyramid/README.md
- subjects/partial_sums/README.md
- subjects/reverse_it/README.md
- subjects/rpn/README.md
Language review of the first rust exam
> 3 review language piscine rustexam 01 c 358

- subjects/inv_pyramid/README.md
Expected function should actually have String as input and output parameter.
> Update inv_pyramid > README.md

- subjects/does_it_fit/README.md
- subjects/expected_variable/README.md
- subjects/macro_calculator/README.md
- subjects/middle_day/README.md
- subjects/mobs/README.md
- subjects/shopping_mall/README.md
Language review of the first quest of the second week.
> 6 review language piscine rustquest 05 c 455

- subjects/chunky/README.md
- subjects/cut-corners/README.md
- subjects/elementary/README.md
- subjects/find-expression/README.md
- subjects/flat/README.md
- subjects/get/README.md
- subjects/index-of/README.md
- subjects/keep-cut/README.md
- subjects/molecules-cells/README.md
- subjects/nasa/README.md
- subjects/pyramid/README.md
- subjects/repeat/README.md
- subjects/reverser/README.md
- subjects/slicer/README.md
- subjects/sums/README.md
- subjects/triangle/README.md
- subjects/unbreakable/README.md
Grammar review of the language in the second JavaScript quest.
> Review language piscine jsloop quest c 54

- subjects/greedy-url/README.md
- subjects/group-price/README.md
- subjects/ion-out/README.md
- subjects/its-a-match/README.md
- subjects/letter-space-number/README.md
- subjects/same-amount/README.md
- subjects/valid-ip/README.md
- subjects/vowel-dots/README.md
Grammar review of the language in the third JavaScript quest.
> Review language piscine jsfind quest c 113

- subjects/bloody-sunday/README.md
- subjects/count-leap-years/README.md
- subjects/date-is/README.md
- subjects/day-of-the-year/README.md
- subjects/dr-strange/README.md
- subjects/get-some-time/README.md
- subjects/match-cron/README.md
- subjects/rebecca-black/README.md
- subjects/unicode-technical-report-35/README.md
Language review of the JS Piscine `time` quest.
> Review language piscine jstime quest c 107

- subjects/diamond_creation/README.md
- subjects/logic_number/README.md
- subjects/ordinal/README.md
- subjects/pangram/README.md
- subjects/pig_latin/README.md
- subjects/rgb_match/README.md
- subjects/rot/README.md
- subjects/scores/README.md
- subjects/searching/README.md
- subjects/spelling/README.md
- subjects/stars/README.md
- subjects/talking/README.md
Language review of the second quest of the second week.
> 7 review language piscine rustquest 06 c 367

- subjects/queens/README.md
Review of the queens exercise.
I'll merge this into @davidrobert99's branch before it is merged.
> 19 review language piscine rustexam 02 c 524

- subjects/borrow_box/README.md
- subjects/box_it/README.md
- subjects/box_recursion/README.md
- subjects/how_many_references/README.md
Language review of the first quest of week 3 (PART 1)
> 10 review language piscine rustquest 07 c 441

- subjects/blood_types/README.md
- subjects/easy_traits/README.md
- subjects/generics/README.md
- subjects/generics_list/README.md
- subjects/traits/README.md
- subjects/vector_operations/README.md
Language review for the first part of the second quest of the third week (Quest 8).
Second part will follow shortly.
> 11 review language piscine rustquest 08 c 382

- subjects/chaikin/README.md
- subjects/chaikin/audit/README.md
Language review of Chaikin's raid in the rust piscine.
> 13 review language piscine rustchaikin c 526

- subjects/matrix_display/README.md
Only one exercise to review here. All the others are done in previous exams and quests.
> Language Review of Exam03

- subjects/lunch_queue/README.md
Language review of a single exercise lunch_queue
It has been done alone, as it was not done as part of a previous language review. It is now only in exam >3
> docs(lunch_queue) correct grammar

- subjects/tron/README.md
- subjects/tron/audit/README.md
Corrects grammar for tron, audit and subject.
> Tron local gameplay c 583

- subjects/chaikin/audit/README.md
By the raid specification, there can be no animation unless there are more than 2 points
> chaikin audit fix

- subjects/chaikin/audit/README.md
Merging @uristdwarf's proposals into master.
maintained that `Escape` terminates the program, so that this remains a mandatory implementation for the raid.
> Uristdwarf proposed changes

- subjects/border_cross/README.md
- subjects/delete_prefix/README.md
- subjects/lifetimes/README.md
- subjects/matrix/README.md
- subjects/matrix_mult/README.md
- subjects/matrix_ops/README.md
`events` is missing. It will be added later
> Quest 9 language review

- js/tests/get-some-time_test.js
for where sunday is the first day of the year.
> fix(get-some-time): add missing test case

- subjects/filter/README.md
- subjects/flow/README.md
- subjects/for-each/README.md
- subjects/long-words/README.md
- subjects/mapper/README.md
- subjects/quantifiers/README.md
- subjects/sweet-curry/README.md
- subjects/using-filter/README.md
- subjects/using-map/README.md
- subjects/using-reduce/README.md
Language review of the call me maybe quest
> Dev 2405 review language piscine js call me maybe quest

- subjects/build-brick-and-break/README.md
- subjects/fifty-shades-of-cold/README.md
- subjects/get-them-all/README.md
- subjects/harder-bigger-bolder-stronger/README.md
- subjects/pimp-my-style/README.md
Language review of first part of dom quest.
> Dev 2411 review language piscine js dom quest

- subjects/events/README.md
color display problem in console section isn't fixed
> updated description to fit the task

- subjects/debounce/README.md
- subjects/get-json/README.md
- subjects/interpolation/README.md
- subjects/keep-trying-or-giveup/README.md
- subjects/throttle/README.md
First part of the language review for the async quest.
> Dev 2399 review language piscine js async quest

- subjects/clonernews/README.md
- subjects/clonernews/audit/README.md
Review of language for clonernews raid (js piscine)
> Dev 2419 review language piscine js clonernews raid

- subjects/oddlength/README.md
> docs: Add description for oddlength

- subjects/printevenarguments/README.md
Add readme for printevenarguments subject.
> docs: add readme for printevenarguments subject

- subjects/popint/README.md
Add readme for popint subject.
> docs: Add readme for popint subject

- subjects/concatenate/README.md
Add readme for subject concatenate
> docs: Add readme for subject concatenate

- subjects/sum/README.md
> docs: Add readme for sum subject

- subjects/evenlength/README.md
Add readme file for evenlength subject.
> docs: Add readme file for evenlength subject

- subjects/delete/README.md
Write readme for delete subject
> Write readme for delete subject

- subjects/pingpong/README.md
Add readme file with the instructions
> 1140 ping pong

- js/tests/test.mjs
- js/tests/verydisco-forever_test.mjs
- subjects/select-and-style-dom/README.md
this fix some tests with new version of nodejs
> fix(js): replace base64 url trick by temp file

- subjects/listsort/README.md
- subjects/sortedlistmerge/README.md
- subjects/sortlistinsert/README.md
There are still some improvements to make - but we will make those after the current round of in progress selection piscines
> docs(go quest 11): correct grammar of NodeI exercises

- subjects/listlast/README.md
Specify to return `Data` instead of element.
> docs: Correct instructions about what to return

- subjects/listfind/README.md
Specify that is the address of the data that has to be returned.
> docs: Be more specific with the instructions

- subjects/listat/README.md
Specify that what the function should take is a pointer to the head node of the list, not to the list.
> docs: Correct description

- subjects/flags/README.md
Expected output reference: https://github.com/01-edu/go-tests/blob/master/solutions/flags/main.go
> Fix the example to match the expected output

- subjects/get-json/README.md
- subjects/pimp-my-style/README.md
Fix semantics from 'First' to 'Last'
> DEV-3034 - DEV-3034-pimp-my-style-fifo-lifo-typo

- subjects/fibonacci2/README.md
- subjects/scalar/README.md
Resolve two typos in the rust piscine.
> Resolve typos in the rust piscine

- subjects/looping/README.md
Now there is no difference in output for the word "trial" in case the user succeeds on the first one.
rust-test needs to be updated also to reflect the change.
> docs(looping): Removing one edge case

- subjects/cut-corners/README.md
Make all limitations more explicit in subject
> Improve cut-corners subject

- subjects/ascii-art/audit/README.md
The exclamation marks were not properly escaped, so the actual output did not match the expected result in the audit file.
Here is a small program to test args with node
```js
console.log(process.argv[2])
```
```console
$ node index.js "\\!\" #$%&'()*+,-./"
```
```console
$ node index.js "hello There 1 to 2\!"
```
> [GitHub issue #1419] ascii-art audit: Escape exclamation marks

- subjects/shopping_mall/README.md
3 functions didn't match the name in the tests
> 1413-shopping_mall-subject fix: functions names

- subjects/pig_latin/README.md
- subjects/piglatin/README.md
Not in every language the vowels are just `aeiou`. Added the specification.
> Docs: specify what is considered a vowel in this exercise

- subjects/matrix_ops/README.md
remove a typo according to student feedback
> docs(matrix_ops): remove typo

- subjects/box_it/README.md
- subjects/matrix_ops/README.md
- subjects/traits/README.md
subject clarified according to student input
> 1415 box it subject

- subjects/unwrap_or_expect/README.md
Rewrite the subject completely to give more meaningful learning experience to students.
rust-tests repo needs to be updated too
> docs(unwrap_or_expect): rewrite the subject

- subjects/matrix_ops/README.md
- subjects/traits/README.md
as per student suggestion, `fat_content` is now described as "decimal fraction" and not as percentage
> 1431 traits subject

- subjects/sales/README.md
Improved the subject as per student feedback and also solved two typos
> 1448 sales subject

- subjects/commits_stats/README.md
- subjects/commits_stats/attachments/commits.json
add a missing attachment as per student request + fixing a typo
> 1434 commits stats subject

- subjects/union/README.md
Correct usage example to print new line
> 1433 union inconsistent newline requirement between example and test

- subjects/borrow_box/README.md
Subject do not ask to increment `nbr_of_games` anymore and code example has better args names for `new()`
> 1416 borrow box subject

- subjects/iterators/README.md
now the iterator trait is well implemented and tested and collatz() return value in line with idiomatic rust first example formatting is clearer
provided testing main() has also edge cases 0 and 1
I will merge tests and public at the same time to avoid inconsistencies.
> 1460-DEV-3511 feat(iterators): improve consistency and clarity

- subjects/ascii-art/fs/audit.md
- subjects/ascii-art/output/audit.md
> Github issue 1491 | quotes in invalid input audit questions

- subjects/shopping_mall/README.md
also improve readability of output for the example main.rs
> feat(shopping_mall): remove not neutral function

- subjects/podiumposition/README.md
Created and added README.md for new go exercise podiumposition.
> DEV-3502-feat(piscine-go): add README.md for new go exercise podiumposition

- subjects/reversemenuindex/README.md
Created and added README.md for new go exercise reversemenuindex
> DEV-3514-feat(piscine-go): add README.md for new go exercise reversemenuindex

- subjects/dealapackofcards/README.md
Created and added new go exercise dealapackofcards.
> DEV-3519-feat(piscine-go): add README.md for new go exercise dealapackofcards

- subjects/localhost/README.md
- subjects/localhost/audit/README.md
due to git wrong pull/merge previous commits have been lost. commit messages relevant to this project are transcripted here as reference:
commit 05f8f75d05f1f26315f96e60fa5c8e2f1e85f4d3
Author: mikysett <mikysett@gmail.com>
Date:   Mon Sep 26 16:53:53 2022 +0100
feat(localhost): complete subject and audit
audit completely refactored and improved (more clear, more questions, irrelevant question removed, bonuses updated)
small improvements on the subject
commit fd3a2a00aec6c58c9c34b1c78c6d3d0bbad11b74
Author: mikysett <mikysett@gmail.com>
Date:   Thu Sep 22 17:45:38 2022 +0100
feat(localhost): change bonuses
php file with mysql is redundant (a CGI must already be implemented).
to suggest rewriting it with a different language looks like a nice challenge, maybe a bit big for a bonus
commit …
> feat(localhost): subject and audit ready for review

- subjects/rockandroll/README.md
Created README.md for the new go exercise rockandroll
> DEV-3505-feat(piscine-go): add README.md for new go exercise rockandroll

- subjects/jumpover/README.md
Added missing import piscine and fixed the title heading.
> DEV-3500-fix(jumpover): add missing import piscine and add second # to the title

- subjects/tuples_refs/README.md
need to be merged at the same time of `rust-tests`
> DEV-3192 Refactor-Tuples-Refs Change id type for more idiomatic rust

- subjects/shoppinglistsort/README.md
Created the README.md for the new go exercise shoppinglistsort
> DEV-3517-feat(pisicine-go): add README.md for new exercise shoppinglistsort

- subjects/tic_tac_toe/README.md
to merge at same time of `rust-tests`
> DEV-3214 Refactor-Tic-Tac-Toe All results are now lowercase

- subjects/simple_hash/README.md
need to be merged at the same time of rust-tests.
> DEV-3237 Data Simple hash refactory to have a more useful and stimulating intro to hash maps

- subjects/cipher/README.md
merge at same time of `rust-tests`
> DEV-3253 Refactor-Cipher Fix typos and remove useless notions

- subjects/error_types/README.md
to merge at same time of `rust-tests`
> DEV-3255 Error-types Improve style and names

- subjects/easy_traits/README.md
also improve the arguments names
to update at the same time of `rust-tests`
> DEV-3470 Docs-Easy-traits Fix prototype error and add pub where necessary

- subjects/borrow_me_the_reference/README.md
need to be merged at same time of `rust_tests`
> DEV-3213 Borrow-me-the-reference Remove need to use meval crate

- subjects/pig_latin/README.md
to be merged at same time of `rust_tests`
> DEV-2556 Pig-latin Fix wrong solution

- subjects/shoppinglistsort/README.md
Fixed shoppinglistsort instructions.
> DEV-3571-docs(shoppinglistsort): fix instructions

- subjects/min_and_max/README.md
new exercise for rust exam: `min_and_max`
> DEV-3800 new exercises for rust exam: min_and_max

- js/tests/keycodes-symphony-dom_test.mjs
> DEV-3938 fix keycode-symphony-dom test

- subjects/ascii-art/justify/audit.md
quote marks are misplaced in two audit questions
> docs(ascii-art-justify): fix audit

- subjects/zappy/README.md
adding clarifications to the readme
> Zappy subject Issue #1587 

- subjects/blood_types_s/README.md
B+ type can't donate to O+, O
reference - https://www.inovablood.org/donate-blood/ideal-donation-for-your-blood-type/
> Incorrect table for B+ type blood donation: B+ can't donate to O+, O-

- subjects/canyoucount/README.md
Add readme for canyoucount #1258
> DEV-3892-docs: Add readme for canyoucount subject #1258

- subjects/replaceeven/README.md
> DEV-3887-add(replaceeven): subject

- subjects/multorsum/README.md
> DEV-3886-1270 multorsum

- subjects/rectperimeter/README.md
> DEV-3884-add Subject: Rect Perimeter exercise

- subjects/issamestring/README.md
> DEV-3883-subject for Exercise is same string

- subjects/returna/README.md
- created branch to fix old PR that had too many conflicts
> DEV-3395-docs(returna): created a subject for returna exercise

- subjects/only1/README.md
> DEV-3387 new go exercise only 1 - subject

- subjects/ascii-art/audit/README.md
- subjects/ascii-art/justify/audit.md
- subjects/ascii-art/output/audit.md
Add specification about which shell to use to have consistent audits for ascii-art main and optional projects.
> DEV-3999 add details to make audits consistent

- subjects/binarycheck/README.md
> DEV-3409-new go exercise print if

- subjects/count-character/README.md
- exercise was wrongly removed from master
- added again
> DEV-4022-fix(countcharacter): added count character

- subjects/manipulate-entries/README.md
Add the `usage` section in README
> DEV-4016 - improve manipulate-entries subject

- js/tests/gatecrashers_test.mjs
- subjects/gatecrashers/README.md
It should be necessary to add `global._fetch = fetch` at line 10 of file `test.mjs` to run the tests.
At the moment the test spawn the server but do not kill it after testing (we may want to change this in a future commit).
> feat(gatecrashers): add a new exercise to js node quest

- .github/workflows/docker-images.yml
This github workflow will automate the building and publication of : 
-  The sh (shell) tests image ghcr.io/01-edu/test-sh:latest
-  The JS (JavaScript) tests image ghcr.io/01-edu/test-js:latest
-  The DOM tests image ghcr.io/01-edu/test-dom:latest
> DEV-4037 adding image build workflow public repo

- subjects/ascii-art-web/audit/README.md
Remove double quotes to make audit asks coherent with the subject and solution example provided
> DEV-4067 improve ascii-art-web audit

- subjects/ascii-art/fs/README.md
> remove spurious blank lines in examples

- subjects/ascii-art/fs/README.md
Remove empty blank lines from the example
> Improve ascii-art-fs subject 

- subjects/sumthemall/README.md
Add readme for sumthemall subject
> DEV-3881-docs: Add readme for sumthemall subject

- subjects/groupie-tracker/search-bar/audit.md
> docs(groupie-tracker-search-bar): make audit question accurate

- subjects/ispowerof2/README.md
Add definition of power of 2 in the subject
> DEV-4008 - improve ispowerof2 subject

- sh/tests/input-redirection_test.sh
- sh/tests/solutions/input-redirection.sh
- subjects/devops/input-redirection/README.md
New exercise for DevOps branch, scripting piscine, quest 3
> DEV-3926 Add new exercise - Input redirection

- sh/tests/remake_test.sh
- sh/tests/solutions/remake.sh
- subjects/devops/remake/README.md
Add new exercise for scripting piscine
> DEV-3945 - remake exercise

- subjects/bloody-sunday/README.md
"There was a mistake in the word 'teh', it should have been 'the'. I also made some improvements to the grammar."
> Fix small mistake

- sh/tests/joker-num_test.sh
- sh/tests/solutions/joker-num.sh
- subjects/devops/joker-num/README.md
New exercise for scripting piscine, devops branch
> DEV-3952 joker-num

- subjects/ai/numpy/audit/README.md
The previous solution wasn't accurate.
Replace it for the right one.
Not relevant.
> DEV-4284 replace solution in football tournament

- subjects/crossword/README.md
new line in the beginning of output removed as it is not consistent with the audit questions
> DEV-4283 - Clarify crossword subject

- sh/tests/Dockerfile
To fix this error in the tests:
`file-struct_test.sh: line 11: tree: command not found`
Adding the tree command in the Dockerfile to fix a bug with the scripting tests
> Explain the details of the implementation and the reasoning behind it. What alternative approaches were considered and why was this …
> DEV-4286: add tree to the dockerfile

- sh/tests/hard-perm_test.sh
- subjects/devops/hard-perm/README.md
- subjects/devops/strange-files/README.md
> fix(devops): fixing typos and changing perms in the exercise hard-perm

- sh/tests/in-the-dark_test.sh
- subjects/devops/in-the-dark/README.md
remove unnecessary test in the exercise in-the-dark add clarification in the readme of in-the-dark
> DEV-4290: fixing devops branch

- subjects/devops/find-files-extension/README.md
- subjects/devops/master-the-ls/README.md
> DEV-4296: fixing readmes in the scripting piscine

- subjects/invert/README.md
Inaccurate description
Specify what to return
Doesn't apply
> DEV-4307 docs(invert): clarify what to return

- subjects/devops/deep-in-system/README.md
- subjects/devops/deep-in-system/audit/README.md
- subjects/devops/numerical_operations/README.md
add new python exercise to scripting piscine
> DEV-4180 numerical-operations

- subjects/devops/string_tokenizer/README.md
> DEV-4323: string_tokenizer

- subjects/devops/shopping/README.md
New exercise for scripting piscine quest 6 - subject
> DEV 4184 - shopping exercise

- subjects/devops/merge_two/README.md
add new python exercise to scripting piscine
subject and tests/solution should be merged at the same time
> DEV-4318 merge-two

- subjects/devops/credentials_searches/README.md
> DEV-4328 docs(credentials_searches): add description of exercise

- subjects/devops/flexible_function/README.md
Add description for the scripting piscine exercise
> DEV-4329 docs(flexible_function): add  description for exercise

- subjects/devops/write_file/README.md
> DEV-4326: write_file

- subjects/devops/read_file/README.md
> DEV-4325: read_file

- subjects/devops/object_to_json/README.md
new exercise for scripting piscine quest 7
> DEV-4320: object_to_json - scripting piscine exercise

- subjects/devops/string_tokenizer_count/README.md
> DEV-4337 docs(string_tokenizer_count): add description for exercise

- subjects/devops/skip_secrets/README.md
Add new python scripting piscine exercise
> DEV-4327 - skip secrete new python exercise

- subjects/devops/candidates_checker/README.md
new python exercise for scripting piscine quest 7
`public` and `python-tests` branches should be merged at the same time
> DEV-4321 candidates checker

- subjects/devops/deep-in-net/README.md
- subjects/devops/deep-in-net/audit/README.md
> There was some unclear instructions 
> English Review
> deep-in-net new subject and audit version

- subjects/mobs/README.md
`public` and `rust-tests` should be merged at the same time.
[Related issue](https://github.com/01-edu/public/issues/1809)
> DEV 4455 fix-confusing-structure-for-mobs-rust-piscine

- subjects/hello-there/README.md
Adds a brief description of how to execute a JavaScript file with Node.js.
> DEV-4445 Add description of how to execute js with node in hello there

- subjects/make-your-game/README.md
> Complains about the questions about layers in the audit.
> add info about the use of layer in the README
> DEV-4456 Add info about layers to Make Your Game

- subjects/crossword/README.md
- subjects/crossword/audit/README.md
adding test case requested by an issue
> DEV-4466: crosword

- subjects/harder-bigger-bolder-stronger/harder-bigger-bolder-stronger.html
Small fix for wrongly added file
> fix(harder-bigger-bolder-stronger): add right css file to html

- subjects/devops/strange-files/README.md
consistant file name in the subject and corresponding to the test
> Piscine-Scripting Quest 1 : Update README.md strange-files

- subjects/highest/README.md
[related github issue](https://github.com/01-edu/public/issues/1838)
> DEV-4482 highest-rust-piscine-unclear-function-prototype-in-subject

- subjects/devops/json-researcher/README.md
the curl command doesn't give any output, maybe explicit the exemple by updating the readme like this ?
> Piscine-Scripting Quest 1 json-researcher : Update README.md

- subjects/mobile-dev/circle/README.md
- subjects/mobile-dev/data-structures/README.md
- subjects/mobile-dev/intro/README.md
- subjects/mobile-dev/max-num/README.md
- subjects/mobile-dev/named-optional-sum/README.md
- subjects/mobile-dev/named-required-sum/README.md
- subjects/mobile-dev/optional-sum/README.md
- subjects/mobile-dev/person/README.md
- subjects/mobile-dev/plain-sum/README.md
- subjects/mobile-dev/student/README.md
- subjects/mobile-dev/university/README.md
- subjects/mobile-dev/variables/README.md
Review language of the flutter piscine
> DEV-4178 review language flutter piscine

- subjects/forum/README.md
- subjects/real-time-forum/README.md
- subjects/real-time-forum/audit/README.md
These will be enforced later here in audits, related to this issue: DEV-4669
> DEV-4669 Describe restrictions for frontend frameworks in forum and real-time-forum

- sh/tests/json-researcher_test.sh
Add boilerplate to test as in `who-are-you_test.sh` that uses `curl`
> DEV-4480: fix test for json-research

- subjects/blockchain/send-transaction-to-peer/README.md
- improve format of bullet points stating what is required
- run prettier
> DEV-4508 - update subject of send-transaction-to-peer

- subjects/basicatoi/README.md
Based on feedback from an issue in public.
> DEV-4671 docs(basicatoi): replace preposition for clarity

- subjects/friend-support/README.md
> DEV-4747: friend-support link fix

- subjects/personal-shopper/README.md
- subjects/tell-me-how-many/README.md
Fix the grammar in the subjects
> DEV-4752: tell-me-how-many/personal-shopper typos

- subjects/cut-corners/README.md
add example of usage for better understanding
> DEV-4749: cut-corners add example

- subjects/graphql/README.md
- subjects/graphql/audit/README.md
[DEV-4670](https://01talent.atlassian.net/browse/DEV-4760)
[DEV-4670]: https://01talent.atlassian.net/browse/DEV-4670?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV-4760 modify graph ql project to require an access token

- subjects/devops/hard-perm/README.md
The readme needs improvement because we are removing the previous exercise that introduced this one
> DEV-4798: hard-perm readme

- subjects/devops/bin-status/README.md
- subjects/devops/calculator/README.md
- subjects/devops/check-user/README.md
- subjects/devops/custom-ls/README.md
- subjects/devops/hard-conditions/README.md
fix the usage of bin status
format readmes of other exercises
> DEV-4858: bin status

- subjects/atm-management-system/README.md
- subjects/atm-management-system/audit/README.md
Update the subject and audit of the exercise to be in line with the video example provided in the subject
> DEV-4786: update subject and audit of `atm-management-system`

- subjects/devops/division/README.md
fix the error message according to sol
> Devops: Division exercise

- subjects/devops/calculator/README.md
- subjects/devops/check-user/README.md
- subjects/devops/grades/README.md
- subjects/devops/hard-perm/README.md
- subjects/devops/head-and-tail/README.md
- subjects/devops/in-back-ground/README.md
- subjects/devops/joker-num/README.md
- subjects/devops/kept-promise/README.md
- subjects/devops/largest/README.md
- subjects/devops/left/README.md
- subjects/devops/remake/README.md
Improve the readmes in  scripting piscine
> DEV-4874: scripting-piscine improving readmes

- subjects/blockchain/exploring-blockchains/README.md
- fix broken link in Resources section
- fix small typo
> fix(exploring-blockchains): update README

- subjects/devops/numerical_operations/README.md
tempo fix for numerical operations
> numerical operations

- subjects/devops/numerical_operations/README.md
> numerical-operations

- subjects/mobile-dev/quizz-app/README.md
fixing structure of the readme
adding more instructions to make the project easier to achieve
> DEV-4655: quizz-app Readme

- subjects/mobile-dev/quizz-app/audit/README.md
fixing structure of the audit
adding more questions according to the readme
> DEV-4656: quizz-app Audit

- subjects/devops/backup_manager/README.md
- subjects/devops/backup_manager/audit/README.md
improve readme and audit by adding examples requested by the students
> DEV-4932: backup-manager improve readme and audit

- subjects/cybersecurity/passive/README.md
- subjects/cybersecurity/passive/audit/README.md
- Align audit asks with the example provided in the subject
- Introduce small improvements in the subject
> DEV 4931 improve passive audit

- sh/tests/solutions/to-git-or-not-to-git.sh
- sh/tests/to-git-or-not-to-git_test.sh
- subjects/to-git-or-not-to-git/README.md
Due to some changes on the permissions for the students, this exercise was no longer  possible to complete
it was remade and the order that it appears on the quest was changed.
> DEV-5013 to-git-or-not-to-git remake

- subjects/mobile-dev/bizz-card/README.md
Fixing the readme struct and adding more instructions to make the project easy to achieve
> DEV-4643: bizz-card Readme

- subjects/mobs/README.md
Add a notion link to the subject
> feat(mobs): add notions to subject

- subjects/mobile-dev/bouncer/README.md
- subjects/mobile-dev/bouncer/audit/README.md
Fix the structure and add clarity to readme and audit
Add Bonus part and questions
> DEV-4737: bouncer fix readme and audit

- subjects/mobile-dev/kahoot/README.md
- subjects/mobile-dev/kahoot/audit/README.md
> DEV-4999: kahoot audit and readme

- subjects/remote/README.md
> Update README.md from remote admin-sys branch

- subjects/ai/numpy/README.md
add the link to the provided file in the readme of the exercise numpy
> DEV-5043: add a link to the numpy exercise

- subjects/mobile-dev/movie-list/audit/README.md
fixing structure of the audit and improving the questions
> DEV-4680:movie-list audit

- subjects/mobile-dev/secure-notes/README.md
- subjects/mobile-dev/secure-notes/audit/README.md
fix audit and readme for secure-notes
> DEV-4942: secure notes audit and readme

- subjects/mobile-dev/movie-list/README.md
fixing structure of the readme and adding info to clarify subject
> DEV-4679: movie-list

- subjects/mobile-dev/hacker-news/README.md
- subjects/mobile-dev/hacker-news/audit/README.md
> DEV-4922: hacker-news fix audit and readme

- subjects/mobile-dev/bloc-counter/README.md
- subjects/mobile-dev/bloc-counter/audit/README.md
fix bloc-counter audit and readme
> DEV-4941: bloc-counter audit and readme

- js/tests/for-each_test.js
- add check for returned value(s)
> DEV-4935 - improve exercise 'for-each' tests

- subjects/mobile-dev/twenty-forty-eight/README.md
- subjects/mobile-dev/twenty-forty-eight/audit/README.md
fix audit and readme of twenty-forty-eigh
> DEV-4997 twenty-forty-eight readme and audit 

- subjects/mobile-dev/sky-map/README.md
- subjects/mobile-dev/sky-map/audit/README.md
sky-map audit and readme fixes
> DEV-4943 sky-map audit and readme

- subjects/mobile-dev/stock-market/README.md
- subjects/mobile-dev/stock-market/audit/README.md
fix audit and readme for stock-market
> DEV-4944: stock-market audit and readme

- subjects/mobile-dev/secure-messenger/README.md
- subjects/mobile-dev/secure-messenger/audit/README.md
fix audit and readme for  secure-messenger
> DEV-5000: secure-messenger  audit and readme

- subjects/java-piscine/Capitalize/README.md
- subjects/java-piscine/Capitalize/input.txt
- subjects/java-piscine/Capitalize/result.txt
- subjects/java-piscine/Cat/README.md
- subjects/java-piscine/CatInFile/README.md
- subjects/java-piscine/DoOp/README.md
- subjects/java-piscine/FileManager/README.md
- subjects/java-piscine/FileSearch/README.md
- subjects/java-piscine/SortArgs/README.md
Adding all subjects of the second quest of the java piscine
> docs: adding subjects for quest2 of the java piscine

- subjects/hashcode/README.md
Created new branch with the subject exercise in order to solve the conflicts with the previous branch.
> DEV-3200-feat(hashcode): add README.md for new go exercise hashcode

- subjects/java-piscine/StarConstructors/README.md
- subjects/java-piscine/StarGalaxy/README.md
- subjects/java-piscine/StarGetters/README.md
- subjects/java-piscine/StarInheritance/README.md
- subjects/java-piscine/StarMass/README.md
- subjects/java-piscine/StarOverride/README.md
- subjects/java-piscine/StarPlanet/README.md
- subjects/java-piscine/StarProperties/README.md
- subjects/java-piscine/StarStatic/README.md
- subjects/java-piscine/StarUtils/README.md
adding subjects for quest3 of the java piscine
> docs: adding subjects for quest3 of the java piscine

- subjects/java-piscine/AdventureAbstract/README.md
- subjects/java-piscine/AdventureCatch/README.md
- subjects/java-piscine/AdventureCharacter/README.md
- subjects/java-piscine/AdventureException/README.md
- subjects/java-piscine/AdventureInterface/README.md
- subjects/java-piscine/AdventureMonster/README.md
- subjects/java-piscine/AdventureSorcerer/README.md
- subjects/java-piscine/AdventureTemplar/README.md
- subjects/java-piscine/AdventureUtils/README.md
- subjects/java-piscine/AdventureWeapon/README.md
adding subjects for quest 4 of the java piscine
> docs: adding subjects for quest 4 of the java piscine

- subjects/java-piscine/KeepTheChange/README.md
- subjects/java-piscine/ListContains/README.md
- subjects/java-piscine/ListEqual/README.md
- subjects/java-piscine/ListSearchIndex/README.md
- subjects/java-piscine/MapEqual/README.md
- subjects/java-piscine/MapInventory/README.md
- subjects/java-piscine/SetEqual/README.md
- subjects/java-piscine/SetOperations/README.md
- subjects/java-piscine/SortList/README.md
- subjects/java-piscine/Wedding/README.md
- subjects/java-piscine/WeddingComplex/README.md
- subjects/java-piscine/streamCollect/README.md
- subjects/java-piscine/streamMap/README.md
- subjects/java-piscine/streamReduce/README.md
dding subjects for quest 5 of the java piscine
> docs: adding subjects for quest 5 of the java piscine

- subjects/java-piscine/DifferenceBetweenDate/README.md
- subjects/java-piscine/FormatDate/README.md
- subjects/java-piscine/ParseDate/README.md
- subjects/java-piscine/RegexMatch/README.md
- subjects/java-piscine/RegexReplace/README.md
adding subjects for quest 6 of the java piscine
> docs: adding subjects for quest 6 of the java piscine

- subjects/java-piscine/Quest7-DesingPattern/Builder/README.md
- subjects/java-piscine/Quest7-DesingPattern/Decorator/README.md
- subjects/java-piscine/Quest7-DesingPattern/Factory/README.md
- subjects/java-piscine/Quest7-DesingPattern/Observer/README.md
- subjects/java-piscine/Quest7-DesingPattern/Singleton/README.md
- subjects/java-piscine/Quest7-DesingPattern/Strategy/README.md
adding subjects for quest 7 of the java piscine
> docs: adding subjects for quest 7 of the java piscine

- subjects/user-experience/piscine-ui/atomic-design/README.md
- subjects/user-experience/piscine-ui/atomic-design/audit/README.md
- subjects/user-experience/piscine-ui/building-an-interface/README.md
- subjects/user-experience/piscine-ui/building-an-interface/audit/README.md
- subjects/user-experience/piscine-ui/colors-and-moodboard/README.md
- subjects/user-experience/piscine-ui/heuristics/README.md
- subjects/user-experience/piscine-ui/heuristics/audit/README.md
- subjects/user-experience/piscine-ui/rules/README.md
- subjects/user-experience/piscine-ui/rules/audit/README.md
- subjects/user-experience/piscine-ux/athlete-keep-hydrated/README.md
- subjects/user-experience/piscine-ux/athlete-keep-hydrated/audit/README.md
- subjects/user-experience/piscine-ux/going-on-holidays/README.md
- subjects/user-experience/piscine-ux/going-on-holidays/audit/README.md
- subjects/user-experience/piscine-ux/music-on/README.md
- subjects/user-experience/piscine-ux/seamstress/README.md
- subjects/user-experience/piscine-ux/seamstress/audit/README.md
- subjects/user-experience/piscine-ux/sunday-night-movie/README.md
- subjects/user-experience/piscine-ux/sunday-night-movie/audit/README.md
- subjects/user-experience/piscine-ux/teenage-drama/README.md
- subjects/user-experience/piscine-ux/teenage-drama/audit/README.md
- subjects/user-experience/piscine-ux/the-olympics/README.md
- subjects/user-experience/piscine-ux/the-olympics/audit/README.md
The exercises within each quest have been moved into the correct order. For reference, here is the order:
Ex 1 = User interview
Ex 2 = Analytics
Ex 3 = Personas
Ex 4 = User Journey
Ex 5 = Problem Statement
Ex 6 = Ideation
Ex 7 = Prototyping
Ex 1 = Interview Guide
Ex 2 = Run Interviews
Ex 3 = Affinity Diagram
Ex 4 = Problem Statement
Ex 5 = Ideation
Ex 6 = User Flow
Ex 7 = Prototyping
Ex 1 = Competitive Analysis
Ex 2 = Surveys
Ex 3 = Broadcast Strategy
Ex 4 = Interviews
Ex 5 = Personas
Ex 6 = User Journey
Ex 7 = Problem Statement
Ex 1 = Ideation A
Ex 2 = Ideation B
Ex 3 = Ideation C
Ex 4 = User Flow
Ex 5 = Prototyping
Ex 6 = Animation
Ex 7 = Test
Ex 1 = Heuristics
Ex 2 = Site map
Ex 3 = JTBD
Ex 4 = Card Sorting
Ex 5 = Wireframes
Ex 6 = Test protocol
Ex 7 = Run 5 tests
Ex 1 = User Flow
Ex 2 …
> CON-1055: Condense piscine quests into single files per quest.

- subjects/printif/README.md
add a missing subject for go checkpoint new exercises
> docs(printif): add subject

- subjects/java/piscine/FloatOperations/README.md
- subjects/java/piscine/IntOperations/README.md
- subjects/java/piscine/ListEquals/README.md
- subjects/java/piscine/MapEquals/README.md
- subjects/java/piscine/SetEquals/README.md
- subjects/java/piscine/SetOperations/README.md
- subjects/java/piscine/StringContains/README.md
fix java piscine typos in subjects and folders names
> fix(java-piscine): fix java piscine typos in subjects and folders names

- subjects/mobile-dev/chess/resources/README.md
Update chess resources README to properly start a new game instance using the provided server
> CON-1654 improve chess resource

- subjects/doop/README.md
- add new line after operation results as in the expected results
> CON-1850 make doop subject example coherent with expected solution

- subjects/java/piscine/StringReplace/README.md
change StringContain -> StringReplace
> fix: change StringContain -> StringReplace

- subjects/java/piscine/DoOp/README.md
> fix: fix operands wrong order

- subjects/java/LetsPlay/README.md
- subjects/java/LetsPlay/audit/README.md
> Con 1756 markdown let s play java project

- subjects/cybersecurity/passive/audit/README.md
- make it yes/no instead of a/b case
> CON-1916 clarify passive audit question

- subjects/java/piscine/Decorator/README.md
fix getCalories method return String -> int
> fix: fix getCalories method return String -> int

- subjects/java/raids/jraffic/README.md
- subjects/java/raids/jraffic/audit/README.md
> CON-1816-MARKDOWN-road-intersection-raid-for-java-piscine

- subjects/atm-management-system/audit/README.md
[related issue](https://github.com/01-edu/public/issues/2115)
> CON-1926-fix-audit

- subjects/atm-management-system/README.md
make the calculation of monthly interests an explicit requirement
> CON-1930-calculate-interest-in-audit-atm-management-system

- subjects/my-ls-1/README.md
- subjects/my-ls-1/audit/README.md
add the restriction of the os/exec package in the subject and audi
> CON-1932: restrict the use of package in my-ls

- subjects/real-time-forum/audit/README.md
- fix some small grammar mistakes
- clarify audit question mentioned in GitHub issues
> CON-1943 update `real-time-forum` audit

- js/tests/entrypoint.sh
- sh/tests/entrypoint.sh
DEV-5206
If schools enable the code editor for a piscine the students should be able to run their code. For this we need to handle the variable and the code execution on the test image
> DEV-5206 Replace EXAM_MODE & EXAM_RUN_ONLY for public test images

- subjects/mini-framework/README.md
- subjects/mini-framework/audit/README.md
[issue](https://github.com/01-edu/public/issues/2136)
Using React is not explicitly forbidden due to it being formally a "library" and not a "framework".
Still if React would be used it will defeat the purpose of learning how to recreate a reactive system for web UIs.
> CON-1969-Improve-clarity-on-mini-framework

- subjects/atm-management-system/README.md
Fix an error defining wrong pourcentages (examples: 0.07% instead of 7%)
> CON-1973-Update-Subject-and-Audit-of-atm-management

- subjects/java/Angul-it/README.md
- subjects/java/Angul-it/audit/README.md
CON-1759-MARKDOWN-Angul-it-Java-Project
> CON-1759-MARKDOWN-Angul-it-Java-Project

- subjects/java/piscine/Capitalize/README.md
> CON-1981-Fix-missing-imports-in-Capitalize-exercise-runner

- subjects/java/piscine/SetOperations/README.md
remove unrelated text from the example output
> docs: remove unrelated text from the example output

- subjects/mini-framework/README.md
[Github issue](https://github.com/01-edu/public/issues/2182)
> CON-2028-fix-mini-framework-subject-typo

- subjects/java/piscine/RegexReplace/README.md
[Github issue](https://github.com/01-edu/public/issues/2167)
> CON-2030-Fix-wrong-example-code-in-RegexReplace

- subjects/java/projects/lets-play/audit/README.md
to fix the issue #2178 i changed the deprecated annotation the new ones
> CON-2035-replacing-the-deprecated-annotations

- subjects/java/projects/mr-jenk/README.md
- subjects/java/projects/mr-jenk/audit/README.md
adding the subject and the audit file for the mr-jenk project.
> docs: add subject and audit files

- subjects/atm-management-system/audit/README.md
the questions needed some more explaining because of the option to use relational dbs
> CON-2042: atm-management fix the questions

- subjects/java/projects/angul-it/audit/README.md
- subjects/java/projects/mr-jenk/audit/README.md
- subjects/java/projects/nexus/audit/README.md
we have a missing + in the audit bonus questions
> docs: add '+' to the audit bonus questions

- subjects/social-network/README.md
- subjects/social-network/audit/README.md
add some tips and clarify the subject.
> CON-2191 clarify social-network

- subjects/corewar/audit/README.md
- remove strong_* players related questions until strong players will be added to resources
> CON 2260 Update corewar audit

- subjects/system-monitor/README.md
- split feature filtering and selecting processes to monitor into two separate bullet points
> CON-2262 Clarify sytem-monitor subject

- subjects/add-vm/README.md
- subjects/add-vm/audit/README.md
Adding UTM for Apple Silicon users.
> Con 1842 markdown fix virtualization add vm project

- subjects/mini-framework/README.md
- add some small grammar fix
- rephrase sentence to clarify the project objective
> CON-2285 - Update `mini-framework` subject

- subjects/rt/README.md
- Specify that image provided contains a bonus feature.
- Make small grammar fix.
> CON-2287 - clarify `rt` subject

- subjects/login/audit/README.md
remove VirtualBox specification from audit file
> CON-2257-MARKDOWN-Fix-virtualization-login-project

- subjects/ai/training/README.md
- subjects/ai/training/audit/README.md
fix the audit for the ai branch exercise training
> CON-2318 training audit fix

- subjects/ai/model-selection/README.md
remove unnecessary code and update readme
>  CON-2323 model-section 

- subjects/wget/audit/README.md
:fix the commant to make the links right loccally
> CON-2334: wget audit

- subjects/printnbrbase/main.go
- subjects/splitwhitespaces/main.go
- subjects/swap/main.go
Adding the main.go to some of the new exercises in the Checkpoints in order for them to work in the code editor
> CON-2374: Go Checkpoints adding the mains to the exercises  

- subjects/mini-framework/README.md
fix a broken link in the subject
> CON-2378 mini-framework

- subjects/sortwordarr/main.go
fix sortwordarr main.go used in the code editor, its missing imprts
> CON-2380 fix sortwordarr

- subjects/user-experience/piscine-ui/colors-and-moodboard/README.md
> CON-2391 UI-UXX broken link to image

- subjects/btreedeletenode/main.go
- subjects/sortedlistmerge/main.go
Adding the necessary files to the exercises used in the checkpoints
> CON-2392 add files to the readme used in the checkpoint

- subjects/pimp-my-style/README.md
> Simple fix for grammatical error in pimp-my-style/README.md file

- subjects/byebyefirst/main.go
- subjects/cameltosnakecase/main.go
- subjects/checknumber/main.go
- subjects/chunk/main.go
- subjects/concatalternate/main.go
- subjects/countalpha/main.go
- subjects/countcharacter/main.go
- subjects/digitlen/main.go
- subjects/findprevprime/main.go
- subjects/foldint/main.go
- subjects/halfslice/main.go
- subjects/hashcode/main.go
- subjects/iscapitalized/main.go
- subjects/listremoveif/main.go
- subjects/notdecimal/main.go
- subjects/printif/main.go
- subjects/printifnot/main.go
- subjects/rectperimeter/main.go
- subjects/reduceint/main.go
- subjects/removeduplicate/main.go
- subjects/reversesecondhalf/main.go
- subjects/reversestrings/README.md
- subjects/swapfirst/main.go
- subjects/swaplast/main.go
- subjects/thirdtimeisacharm/main.go
- subjects/weareunique/main.go
- subjects/zipstring/main.go
Adding imports to the main.go files used in the checkpoints
> CON-2396 files for checkpoints

- subjects/multiplayer-fps/README.md
- subjects/multiplayer-fps/audit/README.md
CON-2428
Student complained over confusion in the architecture of the project
clarify subject and add bonus question in the audit
> CON-2428 multiplayer-fps 

- subjects/user-experience/piscine-ux/music-on/README.md
- subjects/user-experience/piscine-ux/music-on/audit/README.md
The subject contains technical terminology that has not been adequately defined, leading to potential confusion among students regarding the expected outputs of their work.
> fix music-on subject issue

- subjects/devops/easy-cloud/README.md
CON-####
fix the image for the docs in easy-cloud project in devops branch
change the extension of the file
> CON-2441-fix-easy-cloud-meme-image

- subjects/java/piscine/RegexMatch/README.md
fix subject wrong class name in the test examples.
> RegexMatch subject issue

- subjects/ai/nlp-scraper/README.md
- subjects/ai/nlp-scraper/audit/README.md
Improve `nlp-scraper` project consistency based on student feedback
- add details for question about checking "overfitting" in the audit
- remove not so clear suggestion
- restructure subject and audit to avoid having to submit big files
> CON-2429-update-nlp-scraper-audit

- subjects/card_deck/README.md
> Missing package for Usage program

- subjects/ai/keras-2/audit/README.md
As the same questionw as repeated twice, I just made it shorter.
DEV-#### | SUP-#### | CON-####
> Provide an overview of the solution implemented in this pull request. This should be a high-level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub-compliant [`mermaid`](https://mermaid.live/) graphs to represent the solution visually.
> Explain the details of the implementation and the reasoning behind it. What alternative approaches were considered, and why was this approach chosen?
> Please assign the label `📦 build` If you want to …
> Same Ques was repeated twice in README.md

- subjects/ai/emotions-detector/README.md
- subjects/ai/emotions-detector/audit/README.md
Improve subject and audit clarity:
- Fix some minor grammar issues.
- Improve visualization for the required project structure.
- Specify commands with relative paths from the root project directory in audit and subject.
> CON-2449 clarify subject and audit for `emotion-detector` project

- subjects/user-experience/piscine-ui/colors-and-moodboard/README.md
> Update README.md (font spelling mistake)

- subjects/ai/pandas/audit/README.md
- update expected results for questions 8, 9 and 11
> CON-2466 update expected outcomes for ex2 audit in `pandas` project

- subjects/ai/emotions-detector/README.md
- provide more information about the file provided to solve this project
- reformat the subject and integrate URL in hyperlinks
> CON-2483 clarify the files needed for `emotions-detector` project

- subjects/devops/concat_string/README.md
Replace broken link with a working one
> CON-2497 fix broken link in `concat_string`

- subjects/devops/play-with-containers/audit/README.md
- Fix small format issue.
- Restructure audit question to have a question right after instruction.
> CON-2496 fix broken link in `play-with-containers` audit

- subjects/ai/sp500-strategies/README.md
- subjects/ai/sp500-strategies/audit/README.md
- Fix small grammar mistakes
- Clarify some audit questions
> CON-2488 improve `sp500-strategies` subject and audit

- subjects/mobile-dev/package/README.md
- improve format
- add link to mentioned project
> CON-2518 update `package` subject

- subjects/devops/easy-cloud/README.md
CON-2508
Improve language in docs for easy-cloud
> CON-2508-improve-language-in-easy-cloud-project

- subjects/gaming/nascar-online-alpha/README.md
- subjects/gaming/nascar-online-alpha/audit/README.md
- Fix small grammar mistakes and improve format
> CON-2584 improve `nascar-online-alpha` subject

- subjects/gaming/the-pages/README.md
- Update a link that was referring to U4 with a new one pointing to the official documentation (including U5)
- Improve grammar and format of subject
> CON-2581 improve `the-pages` subject

- subjects/user-experience/piscine-ui/rules/README.md
CON-2618
Missing images
Provide link to the images
> CON-2618 UI/UX branch grids images 

- subjects/user-experience/piscine-ux/athlete-keep-hydrated/README.md
- subjects/user-experience/piscine-ux/athlete-keep-hydrated/audit/README.md
CON-2619
Wrong audit, it was the same as the previous exercise
Create new audit.
> CON-2619 piscine-ux audit for analytics

- subjects/0-shell/README.md
- subjects/0-shell/audit/README.md
CON-2633 SUP-1086
Add restrictions to the project
> Con-2633 Add restrictions 0-shell

- subjects/guess-it-1/audit/README.md
> CON 2681 fix guess-it

- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/README.md
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/app.py
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/requirements.txt
- subjects/mobile-dev/stock-market/resources/mock-stock-data-server/utils.py
> CON-2684 update mock-data server for `stock-market`

- subjects/quadchecker/README.md
CON-2696
Update `quadchecker` subject according to https://github.com/01-edu/go-tests/pull/185
> CON-2696 Update `quadchecker` subject

- subjects/gaming/army-of-one/README.md
- subjects/gaming/army-of-one/audit/README.md
- subjects/gaming/firing-range/README.md
- subjects/gaming/firing-range/audit/README.md
- subjects/gaming/jumpo/README.md
- subjects/gaming/jumpo/audit/README.md
- subjects/gaming/mouse-vr/README.md
- subjects/gaming/mouse-vr/audit/README.md
- subjects/gaming/nascar-online-alpha/README.md
- subjects/gaming/nascar-online-alpha/audit/README.md
- subjects/gaming/stealth-boom/README.md
- subjects/gaming/stealth-boom/audit/README.md
- subjects/gaming/the-pages/README.md
- subjects/gaming/the-pages/audit/README.md
- subjects/gaming/vehicle-physics/README.md
- subjects/gaming/vehicle-physics/audit/README.md
- subjects/gaming/widget-factory/README.md
- subjects/gaming/widget-factory/audit/README.md
- subjects/gaming/zombie-ai/README.md
- subjects/gaming/zombie-ai/audit/README.md
CON-2695
Game Dev assets might be larger than the file maximum size allowed for our schools' Gitea 
Update subjects and audit to allow learners to use GitHub for large files
> CON-2695 update game dev projects' subjects and audits

- subjects/wget/README.md
CON-2701
A flag was missing in the subject
Add flag in the subject so that the student is able to pass the audit
> CON-2701 add flag to `wget` subject

- subjects/java/piscine/Cat/README.md
We are using this exercice for some students and the explanation was unclear. I suggest these changes to make it more clear and more visible.
> ♻️ better explanation for Cat

- subjects/java/checkpoints/almost-palindrom/ExerciseRunner.java
- subjects/java/checkpoints/average-calc/ExerciseRunner.java
- subjects/java/checkpoints/count-char/ExerciseRunner.java
- subjects/java/checkpoints/digitlen/ExerciseRunner.java
- subjects/java/checkpoints/factorial/ExerciseRunner.java
- subjects/java/checkpoints/goodbye-mars/ExerciseRunner.java
- subjects/java/checkpoints/multiplication-table/ExerciseRunner.java
- subjects/java/checkpoints/next-prime/ExerciseRunner.java
- subjects/java/checkpoints/reverse-array/ExerciseRunner.java
- subjects/java/checkpoints/rotate-array/ExerciseRunner.java
- subjects/java/checkpoints/sort-array/ExerciseRunner.java
- subjects/java/checkpoints/strlen/ExerciseRunner.java
- subjects/java/checkpoints/system-logger/ExerciseRunner.java
- subjects/java/checkpoints/unit-converter/ExerciseRunner.java
- subjects/java/checkpoints/universal-greeting/ExerciseRunner.java
[CON-2705](https://01talent.atlassian.net/browse/CON-2705)
[CON-2705]: https://01talent.atlassian.net/browse/CON-2705?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2705  Adding Main Files To The CheckPoints

- subjects/pig_latin/README.md
[CON-2703](https://01talent.atlassian.net/browse/CON-2703)
close #2565 
[CON-2703]: https://01talent.atlassian.net/browse/CON-2703?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2703 update expected output in `pig_latin` subject to be inline with description

- subjects/java/checkpoints/digitlen/ExerciseRunner.java
[CON-2717](https://01talent.atlassian.net/browse/CON-2717)
[CON-2717]: https://01talent.atlassian.net/browse/CON-2717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2717 Fix Digitlen Main issue

- subjects/0-shell/README.md
- subjects/0-shell/audit/README.md
SUP-1086 | CON-2748
Auditors and students had problems understanding the point.
remove mandatory use of low-level system calls and make it bonus
> CON-2748 Update 0-shell

- subjects/displayfile/README.md
[CON-2745](https://01talent.atlassian.net/browse/CON-2745)
[CON-2745]: https://01talent.atlassian.net/browse/CON-2745?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2745 Escape `!`  from `displayfile` subject example command

- subjects/ascii-art/output/README.md
- subjects/ascii-art/output/audit/README.md
[CON-2749](https://01talent.atlassian.net/browse/CON-2749)
[CON-2749]: https://01talent.atlassian.net/browse/CON-2749?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2750 Update `ascii-art-output` audit command

- subjects/countcharacter/README.md
> CON-2756 fix example in `countcharacter`

- subjects/git/README.md
> CON-2758 fix `git` readme

- subjects/ascii-art/fs/README.md
- subjects/ascii-art/output/README.md
> CON-2814 Improve readme for `ascii-art`

- subjects/lines/README.md
[CON-2855](https://01talent.atlassian.net/browse/CON-2855)
[CON-2855]: https://01talent.atlassian.net/browse/CON-2855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2855-fix-grammar-mistakes-in-lines-project

- subjects/lastword/README.md
- subjects/lastword/main.go
[CON-2663](https://01talent.atlassian.net/browse/CON-2663)
[CON-2663]: https://01talent.atlassian.net/browse/CON-2663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2664 [CHECKPOINT-RESTRUCTURE] Update `lastword` to be a function instead of a program

- subjects/firstword/README.md
- subjects/firstword/main.go
[CON-2667](https://01talent.atlassian.net/browse/CON-2667)
[CON-2667]: https://01talent.atlassian.net/browse/CON-2667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2668 [CHECKPOINT-RESTRUCTURE] Update `firstword` subject to require a function instead of a program

- subjects/gcd/README.md
- subjects/gcd/main.go
- add `main.go` to test the function in exam mode
> CON-2660 [CHECKPOINT-RESTRUCTURE] Update `gcd` subject to require a function instead of a program

- subjects/phant0m-writ3r/README.md
[CON-2866](https://01talent.atlassian.net/browse/CON-2866)
[CON-2866]: https://01talent.atlassian.net/browse/CON-2866?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2867 Update-subject-of `phant0m-writ3r`

- subjects/java/checkpoints/reverse-array/ExerciseRunner.java
- subjects/java/checkpoints/rotate-array/ExerciseRunner.java
- subjects/java/checkpoints/sort-array/ExerciseRunner.java
[CON-2915](https://01talent.atlassian.net/browse/CON-2915)
[CON-2915]: https://01talent.atlassian.net/browse/CON-2915?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> docs: adding messing imports to the main files

- subjects/java/checkpoints/first-unique/ExerciseRunner.java
- subjects/java/checkpoints/first-unique/README.md
[CON-2899](https://01talent.atlassian.net/browse/CON-2899)
[CON-2899]: https://01talent.atlassian.net/browse/CON-2899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2899-Markdown-First-Unique-Exercise

- subjects/java/checkpoints/flexisort/ExerciseRunner.java
- subjects/java/checkpoints/flexisort/README.md
[CON-2724](https://01talent.atlassian.net/browse/CON-2724)
[CON-2724]: https://01talent.atlassian.net/browse/CON-2724?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2724 Markdown FlexiSort Exercise

- subjects/borrow_me_the_reference/README.md
[CON-2913](https://01talent.atlassian.net/browse/CON-2913)
close #2627 
[CON-2913]: https://01talent.atlassian.net/browse/CON-2913?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2913 Update `borrow-me-the-reference` subject's example

- subjects/java/checkpoints/top-frequents/ExerciseRunner.java
- subjects/java/checkpoints/top-frequents/README.md
[CON-2902](https://01talent.atlassian.net/browse/CON-2902)
[CON-2902]: https://01talent.atlassian.net/browse/CON-2902?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2902-Markdown-Top-Frequents-Exercise

- subjects/java/checkpoints/single-linkedlist/ExerciseRunner.java
- subjects/java/checkpoints/single-linkedlist/LinkedList.java
- subjects/java/checkpoints/single-linkedlist/README.md
[CON-2817](https://01talent.atlassian.net/browse/CON-2817)
[CON-2817]: https://01talent.atlassian.net/browse/CON-2817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2817 Markdown Single Linked List Exercise

- subjects/matrix_ops/README.md
> CON-2929 Remove imports from `matrix_ops`

- subjects/java/checkpoints/area-calculator/ExerciseRunner.java
- subjects/java/checkpoints/area-calculator/README.md
[CON-2727](https://01talent.atlassian.net/browse/CON-2727)
[CON-2727]: https://01talent.atlassian.net/browse/CON-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2727 Markdown: Area Calculator Exercise

- subjects/java/checkpoints/circular-linkedlist/ExerciseRunner.java
- subjects/java/checkpoints/circular-linkedlist/LinkedList.java
- subjects/java/checkpoints/circular-linkedlist/README.md
[CON-2823](https://01talent.atlassian.net/browse/CON-2823)
[CON-2823]: https://01talent.atlassian.net/browse/CON-2823?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2823 Markdown Circular Linked List Exercise

- subjects/java/checkpoints/day-of-week/ExerciseRunner.java
- subjects/java/checkpoints/day-of-week/README.md
[CON-2872](https://01talent.atlassian.net/browse/CON-2872)
[CON-2872]: https://01talent.atlassian.net/browse/CON-2872?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2872 Markdown Day Of Week

- subjects/java/checkpoints/spiral-matrix/ExerciseRunner.java
- subjects/java/checkpoints/spiral-matrix/README.md
[CON-2839](https://01talent.atlassian.net/browse/CON-2839)
[CON-2839]: https://01talent.atlassian.net/browse/CON-2839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2839 Markdown Spiral Matrix Exercise

- subjects/java/checkpoints/age-finder/ExerciseRunner.java
- subjects/java/checkpoints/age-finder/README.md
[CON-2869](https://01talent.atlassian.net/browse/CON-2869)
[CON-2869]: https://01talent.atlassian.net/browse/CON-2869?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2869 Markdown Age Finder

- subjects/java/checkpoints/perfect-number/ExerciseRunner.java
- subjects/java/checkpoints/perfect-number/README.md
[CON-2911](https://01talent.atlassian.net/browse/CON-2911)
[CON-2911]: https://01talent.atlassian.net/browse/CON-2911?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2911 Markdown Perfect Number Exercise

- subjects/java/checkpoints/is-anagram/ExerciseRunner.java
- subjects/java/checkpoints/is-anagram/README.md
[CON-2827](https://01talent.atlassian.net/browse/CON-2827)
[CON-2827]: https://01talent.atlassian.net/browse/CON-2827?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2827 Markdown Is Anagram Exercise

- subjects/java/checkpoints/double-linkedlist/ExerciseRunner.java
- subjects/java/checkpoints/double-linkedlist/LinkedList.java
- subjects/java/checkpoints/double-linkedlist/README.md
[CON-2820](https://01talent.atlassian.net/browse/CON-2820)
[CON-2820]: https://01talent.atlassian.net/browse/CON-2820?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2820 Markdown Double Linked List Exercise

- subjects/java/checkpoints/date-formatter/ExerciseRunner.java
- subjects/java/checkpoints/date-formatter/README.md
[Con 2721](https://01talent.atlassian.net/browse/CON-2720)
> CON-2721 Markdown date formatter exercise

- subjects/java/checkpoints/factory-blueprint/ExerciseRunner.java
- subjects/java/checkpoints/factory-blueprint/README.md
[CON-2905](https://01talent.atlassian.net/browse/CON-2905)
[CON-2905]: https://01talent.atlassian.net/browse/CON-2905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2890 Markdown Factory Blueprint Exercise

- subjects/java/checkpoints/builder-blueprint/ExerciseRunner.java
- subjects/java/checkpoints/builder-blueprint/README.md
[CON-2893](https://01talent.atlassian.net/browse/CON-2893)
[CON-2893]: https://01talent.atlassian.net/browse/CON-2893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2893 Markdown Builder Blueprint Exercise

- subjects/java/checkpoints/monthly-period/ExerciseRunner.java
- subjects/java/checkpoints/monthly-period/README.md
[CON-2875](https://01talent.atlassian.net/browse/CON-2875)
[CON-2875]: https://01talent.atlassian.net/browse/CON-2875?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2875 Markdown Monthly Period

- subjects/java/checkpoints/singleton-blueprint/ExerciseRunner.java
- subjects/java/checkpoints/singleton-blueprint/README.md
[CON-2887](https://01talent.atlassian.net/browse/CON-2887)
[CON-2887]: https://01talent.atlassian.net/browse/CON-2887?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2887 Markdown Singleton Blueprint Exercise

- subjects/java/checkpoints/todo-list/ExerciseRunner.java
- subjects/java/checkpoints/todo-list/README.md
[CON-2710](https://01talent.atlassian.net/browse/CON-2710)
[CON-2710]: https://01talent.atlassian.net/browse/CON-2710?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2710 Markdown Todo List Exercise

- subjects/has-city/README.md
> CON-2982 Fix subject rendering for `has-city` exercise

- subjects/java/checkpoints/config-protector/ExerciseRunner.java
- subjects/java/checkpoints/config-protector/README.md
> CON-2884 Markdown Config Protector Exercise

- subjects/DPxAI/select-then-style/README.md
[CON-2950](https://01talent.atlassian.net/browse/CON-2950)
[CON-2950]: https://01talent.atlassian.net/browse/CON-2950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2950 Markdown ``DPxAI:Quest00/Ex02``

- dom/embedded-organs_test.js
[CON-2966](https://01talent.atlassian.net/browse/CON-2966)
[CON-2966]: https://01talent.atlassian.net/browse/CON-2966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-2966 Tests ``DPxAI:Quest00/Ex03``

- subjects/printif/README.md
- subjects/printifnot/README.md
CON-3015
SUP-1192 - issues 2 and 3
> CON-3015 Update `printif` and `printifnot` examples to be coherent with subject

- subjects/hiddenp/README.md
> CON-3016 fix subject of `hiddenp`

- subjects/rgb_match/README.md
> CON-3018 Fix subject of `rgb-match`

- subjects/printif/README.md
> CON-3033 Update `printif` subject to be inline with tests

- subjects/itoabase/main.go
> CON-3039 Adding missing main file for the code editor

- subjects/DPxAI/declare-everything/README.md
> CON-3118 Fix ``star-forge`` subject

- subjects/DPxAI/star-forge/README.md
Solve : [CON-3030]('https://01talent.atlassian.net/browse/CON-3030')
[CON-3030]: https://01talent.atlassian.net/browse/CON-3030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3030 Subject for ``Quest01/star-forge``

- subjects/DPxAI/i-win-arguments/README.md
Resolves: [CON-3081](https://01talent.atlassian.net/browse/CON-3081)
[CON-3081]: https://01talent.atlassian.net/browse/CON-3081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3081 Markdown ``Quest01/i-win-arguments``

- subjects/DPxAI/only-if/README.md
Resolve: [CON-3066](https://01talent.atlassian.net/browse/CON-3066)
[CON-3066]: https://01talent.atlassian.net/browse/CON-3066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3066 Markdown DPxAI: `Quest01/only if`

- subjects/DPxAI/good-recipe/README.md
[CON-3063](https://01talent.atlassian.net/browse/CON-3063)
[CON-3063]: https://01talent.atlassian.net/browse/CON-3063?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3063 Markdown for ``Quest01/good-recipe``

- js/tests/transform-objects.json
`https://01talent.atlassian.net/browse/CON-3053`
> CON-3053 Tests(DPxAI): Upload test for quest01 transform-objects

- js/tests/listed.json
`https://01talent.atlassian.net/browse/CON-3057`
> CON-3057 Tests(DPxAI): Upload test for quest01 listed

- js/tests/good-recipe.json
`https://01talent.atlassian.net/browse/CON-3064`
> CON-3064 Tests(DPxAI): upload test for quest01 good-recipe

- js/tests/only-if.json
[CON-3067](https://01talent.atlassian.net/browse/CON-3067)
[CON-3067]: https://01talent.atlassian.net/browse/CON-3067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3067 Tests(DPxAI): upload test for quest01 only-if

- js/tests/star-forge.json
[CON-3074](https://01talent.atlassian.net/browse/CON-3074)
[CON-3074]: https://01talent.atlassian.net/browse/CON-3074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3074 Tests(DPxAI): upload test for quest01 star-forge

- dom/colorful-arms_test.js
[CON-3100](https://01talent.atlassian.net/browse/CON-3100)
[CON-3100]: https://01talent.atlassian.net/browse/CON-3100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3100 Tests(DPxAI): upload test for quest02 colorful-arms

- js/tests/first-function.json
[CON-3077](https://01talent.atlassian.net/browse/CON-3077)
[CON-3077]: https://01talent.atlassian.net/browse/CON-3077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3077 Tests(DPxAI): upload test for quest01 first-function

- js/tests/i-win-arguments.json
[CON-3083](https://01talent.atlassian.net/browse/CON-3083)
[CON-3083]: https://01talent.atlassian.net/browse/CON-3083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3083 Tests(DPxAI): upload test for quest01 i-win-arguments

- subjects/DPxAI/listed/README.md
[CON-3056](https://01talent.atlassian.net/browse/CON-3056)
[CON-3056]: https://01talent.atlassian.net/browse/CON-3056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3056 Add subject for ``Quest01/listed``

- subjects/DPxAI/transform-objects/README.md
[CON-3052](https://01talent.atlassian.net/browse/CON-3052)
[CON-3052]: https://01talent.atlassian.net/browse/CON-3052?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3052 Markdown DPxAI: ``Quest01/transform-objects``

- subjects/DPxAI/first-hello/README.md
> CON-2961 Markdown DPxAI ``Quest02/first-hello``

- subjects/DPxAI/colorful-legs/README.md
> CON-3105 Markdown DPxAI ``Quest02/colorful-legs``

- subjects/DPxAI/colorful-arms/README.md
> CON-3098 Markdown DPxAI ``Quest02/colorful-arms``

- subjects/DPxAI/robots-harmony/README.md
> CON-3109 Add subject for ``Quest03/robots-harmony``

- subjects/DPxAI/robots-harmony/audit/README.md
> CON-3110 Add audit file ``Quest03/robots-harmony``

- subjects/ai/kaggle-titanic/README.md
> CON-3128 Fixing subject ``AI/kaggle-titanic``

- subjects/DPxAI/play-with-variables/README.md
> CON-3006 subject for ``Quest01/play-with-variables``

- subjects/DPxAI/first-function/README.md
- subjects/DPxAI/good-recipe/README.md
- subjects/DPxAI/i-win-arguments/README.md
- subjects/DPxAI/listed/README.md
- subjects/DPxAI/objects-around/README.md
- subjects/DPxAI/only-if/README.md
- subjects/DPxAI/transform-objects/README.md
> CON-3162 Fixing AI Powered Learning section format

- subjects/quad/audit/README.md
> CON-3180: Improve questions in `quad` audit

- subjects/AI.GO/call-it/README.md
- subjects/AI.GO/declare-everything/README.md
- subjects/AI.GO/first-function/README.md
- subjects/AI.GO/first-move/README.md
- subjects/AI.GO/good-recipe/README.md
- subjects/AI.GO/i-win-arguments/README.md
- subjects/AI.GO/listed/README.md
- subjects/AI.GO/only-if/README.md
- subjects/AI.GO/select-then-style/README.md
- subjects/AI.GO/the-skeleton/README.md
- subjects/AI.GO/transform-objects/README.md
This piscine needed to be tested as a student.
Fixes of inconsistencies, unclear instructions and grammar
> [EXTERNAL] Review of subject of the first two quest of AI piscine

- subjects/AI.GO/colorful-arms/README.md
- subjects/AI.GO/robots-harmony/README.md
This piscine needed to be tested as a student.
Fixes of inconsistencies, unclear instructions and grammar
> DEV-#### Review of subject of the third quest and RAID of AI piscine

- subjects/AI.GO/listed/README.md
Resolves: CON-3182
The instructions did not clarify the expected input in a clear way.
Added hints to the subject and more clarifications to the subject.
> CON-3182 Fixing instructions issue in `AI.GO/listed`

- subjects/user-experience/piscine-ui/atomic-design/README.md
- subjects/user-experience/piscine-ui/building-an-interface/README.md
- subjects/user-experience/piscine-ui/colors-and-moodboard/README.md
- subjects/user-experience/piscine-ui/heuristics/README.md
- subjects/user-experience/piscine-ui/rules/README.md
- subjects/user-experience/piscine-ux/athlete-keep-hydrated/README.md
- subjects/user-experience/piscine-ux/athlete-keep-hydrated/audit/README.md
- subjects/user-experience/piscine-ux/going-on-holidays/README.md
- subjects/user-experience/piscine-ux/music-on/README.md
- subjects/user-experience/piscine-ux/seamstress/README.md
- subjects/user-experience/piscine-ux/sunday-night-movie/README.md
- subjects/user-experience/piscine-ux/teenage-drama/README.md
- subjects/user-experience/piscine-ux/the-olympics/README.md
- subjects/user-experience/projects/a-table/audit/README.md
- subjects/user-experience/projects/get-a-room/audit/README.md
- subjects/user-experience/projects/lets-do-some-sports/audit/README.md
- subjects/user-experience/projects/lets-fair-trade/README.md
- subjects/user-experience/projects/lets-fair-trade/audit/README.md
> CON-3194: fix `UI-UX` readme files

- subjects/its-a-match/README.md
fixing a typo on the its-a-match subject | PISCINE-JS
>- `🚀 JS`
> [EXTERNAL] fixing a typo on the its-a-match subject | PISCINE-JS

- subjects/ai/emotions-detector/README.md
- subjects/ai/emotions-detector/audit/README.md
CON-3192
- Resolves CON-3182
- Resolves #2746
> CON-3192 Clarifying an instruction in `Emotions detector`

- subjects/forum/README.md
> [EXTERNAL] Fix duplication typo `forum`

- subjects/brainfuck/README.md
> CON-3267 Improve `brainfuck` instructions

- subjects/social-network/README.md
- subjects/social-network/audit/README.md
[CON-3280](https://01talent.atlassian.net/browse/CON-3280)
[CON-3280]: https://01talent.atlassian.net/browse/CON-3280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3280 refactor `social-network`

- subjects/groupie-tracker/README.md
Improved phrasing in the artists, locations, dates, and relation sections for better clarity. 
Corrected minor grammar issues and improved sentence flow for better comprehension.
> [EXTERNAL] Improve `groupie-tracker` project description

- subjects/ascii-art-web/stylize/audit.md
- subjects/ascii-art-web/stylize/audit/README.md
- subjects/ascii-art/audit/README.md
- subjects/ascii-art/fs/audit/README.md
- subjects/ascii-art/justify/audit/README.md
- subjects/ascii-art/reverse/audit/README.md
- subjects/forum/advanced-features/audit.md
- subjects/forum/advanced-features/audit/README.md
- subjects/forum/audit/README.md
- subjects/forum/security/audit.md
- subjects/forum/security/audit/README.md
- subjects/groupie-tracker/audit/README.md
- subjects/groupie-tracker/visualizations/audit.md
- subjects/groupie-tracker/visualizations/audit/README.md
- subjects/make-your-game/audit/README.md
- subjects/make-your-game/different-maps/audit.md
- subjects/make-your-game/different-maps/audit/README.md
- subjects/make-your-game/history/audit.md
- subjects/make-your-game/history/audit/README.md
- subjects/make-your-game/score-handling/audit.md
- subjects/make-your-game/score-handling/audit/README.md
- subjects/mini-framework/audit/README.md
- subjects/my-ls-1/audit/README.md
- subjects/my-ls/audit/README.md
- subjects/net-cat/audit/README.md
- subjects/tetris-optimizer/audit/README.md
- subjects/wget/audit/README.md
> CON-3289 Improve subjects

- subjects/division_and_remainder/README.md
- subjects/fibonacci2/README.md
- subjects/find_factorial/README.md
- subjects/groceries/README.md
- subjects/looping/README.md
- subjects/matrix_transposition/README.md
- subjects/reverse_string/README.md
- subjects/scalar/README.md
- subjects/speed_transformation/README.md
- subjects/temperature_conv/README.md
- subjects/tuples_refs/README.md
[CON-3260](https://01talent.atlassian.net/browse/CON-3260)
[CON-3260]: https://01talent.atlassian.net/browse/CON-3260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3260 Fix rust piscine's quest-01

- js/tests/elementary_test.js
- js/tests/entrypoint.sh
> DEV-6355 PISCINE JS LOOP ELEMENTARY Error 

- subjects/devops/crud-master-py/audit/README.md
> CON-3344 fix typo in crud master success code 201 to 200

- subjects/make-your-game/README.md
> CON-3382 Fix ink in `make your game`

- subjects/shoppinglistsort/README.md
>  CON-3381 `Shoppinglistsort` add package piscine to the main func

- subjects/road_intersection/README.md
> CON-3380 `Road Intersection` remove bad link

- subjects/forum/advanced-features/README.md
- subjects/forum/authentication/README.md
This PR adds a 'Learned Skills' section at the end of the project description, aligning it with other project descriptions.
> [EXTERNAL] `forum-advanced-features` README.md: add a final section

- subjects/make-your-game/README.md
The original resource link leads to a [404 Not Found](https://www.algolia.com/developers-tech-blog/code-and-deep-dives/performant-web-animations/) page, so I have replaced it with a relevant freeCodeCamp article: [Web Animation Performance Fundamentals – How to Make Your Pages Look Smooth](https://www.freecodecamp.org/news/web-animation-performance-fundamentals/). This new resource provides valuable insights into FPS (Frames Per Second), browser rendering processes, and techniques for achieving smooth animations. It covers best practices for maintaining 60 FPS, optimizing animations for better performance, and avoiding common pitfalls that cause jank. By integrating this authoritative guide, learners will gain a deeper understanding of creating efficient and visually appealing web …
> [EXTERNAL] `make-your-game` Alternative to a not found (404) resource

- employment-tasks/software-engineer/rest-task/README.md
> Before starting, please choose the relevant pull request **Labels**, **Reviewers**, and **Assignees** </br>
> Here are a couple of example tiles of a good pull request:
> - `CON-1234 Title of The Feature or Fix`
> - `[EXTERNAL] Title of The Feature or Fix`
CON-#### | [EXTERNAL]
Added new employment task which can be used to check the knowledge for students before diving into job market
> Provide an overview of the solution implemented in this pull request. This should be a high-level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub-compliant [`mermaid`](https://mermaid.live/) graphs to represent the solution visually.
Added …
> [EXTERNAL] add rest employment task for software engineers

- subjects/firstrune/README.md
- subjects/firstrune/main.go
- subjects/lastrune/README.md
- subjects/lastrune/main.go
- subjects/listforeachif/README.md
- subjects/nrune/README.md
- subjects/printnbr/README.md
- subjects/printnbrbase/README.md
- subjects/rot14/README.md
> CON-3429 `Piscine` small fixes

- subjects/simple_hash/README.md
[CON-3435](https://01talent.atlassian.net/browse/CON-3435)
[CON-3435]: https://01talent.atlassian.net/browse/CON-3435?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3435 Fix `simple_hash` subject

- subjects/profanity_filter/README.md
[CON-3438](https://01talent.atlassian.net/browse/CON-3438)
[CON-3438]: https://01talent.atlassian.net/browse/CON-3438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3438 Fix `profanity_filter` subject

- subjects/handling/README.md
[CON-3442](https://01talent.atlassian.net/browse/CON-3442)
[CON-3442]: https://01talent.atlassian.net/browse/CON-3442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3442 Fix `handling` subject

- subjects/pronoun/README.md
> CON-3429 Add clarification to `pronoun`

- subjects/0-shell/README.md
[CON-3456](https://01talent.atlassian.net/browse/CON-3456)
[CON-3456]: https://01talent.atlassian.net/browse/CON-3456?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3456 Improve `0-shell`

- subjects/card_deck/README.md
[CON-3462](https://01talent.atlassian.net/browse/CON-3462)
[CON-3462]: https://01talent.atlassian.net/browse/CON-3462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3462 Fix `card_deck`

- subjects/lastword/README.md
> [EXTERNAL] refine(`LastWord`): fix backticks

- subjects/shop/README.md
Fix the README title to ensure it stands out clearly as the main heading in the UI.
> [EXTERNAL]: doc(`shop`): fix readme title

- subjects/profanity_filter/README.md
- subjects/scytale_cipher/README.md
- subjects/simple_hash/README.md
[DEV-6744](https://01talent.atlassian.net/browse/DEV-6744)
[DEV-6744]: https://01talent.atlassian.net/browse/DEV-6744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> DEV-6744 Several minor mistakes in Rust piscine quests subjects

- subjects/0-shell/audit/README.md
[CON-3480](https://01talent.atlassian.net/browse/CON-3480)
[CON-3480]: https://01talent.atlassian.net/browse/CON-3480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3480 Fix 0-shell audit

- subjects/ai/backtesting-sp500/audit/README.md
- subjects/ai/credit-scoring/audit/README.md
- subjects/blockchain/exploring-blockchains/audit/README.md
- subjects/devops/backup_manager/audit/README.md
- subjects/forum/advanced-features/audit/README.md
- subjects/git/audit/README.md
- subjects/java/projects/buy-02/audit/README.md
- subjects/localhost/audit/README.md
- subjects/mobile-dev/movie-list/audit/README.md
- subjects/netfix/audit/README.md
- subjects/shop/audit/README.md
> CON-3503 Wrong headings in Audits

- subjects/rt/README.md
Fixed some small grammar mistakes :)
> Before starting, please choose the relevant pull request **Labels**, **Reviewers**, and **Assignees** </br>
> Here are a couple of example tiles of a good pull request:
> - `CON-1234 Title of The Feature or Fix`
> - `[EXTERNAL] Title of The Feature or Fix`
CON-#### | [EXTERNAL]
> Provide an overview of the solution implemented in this pull request. This should be a high-level overview without getting into technical details. If applicable, include screenshots of UI or use GitHub-compliant [`mermaid`](https://mermaid.live/) graphs to represent the solution visually.
> Explain the details of the implementation and the reasoning behind it. What …
> [EXTERNAL] Update README.md

- subjects/java/checkpoints/singleton-blueprint/ExerciseRunner.java
- subjects/java/checkpoints/singleton-blueprint/README.md
> DEV-6758 Some bugs in java exam files and tests 

- subjects/make-your-game/score-handling/audit/README.md
> CON-3606-Fix-make-your-game-score-handling-inconsistency-between-audit-and-subject

- subjects/real-time-forum/typing-in-progress/audit.md
- subjects/real-time-forum/typing-in-progress/audit/README.md
This PR improves the clarity and grammar of the audit instructions related to the typing-in-progress project.
Minor refinements were made to ensure consistent tone, fix grammatical issues (e.g. "when whether"), and enhance readability for students following the steps.
These changes do not affect any logic or functionality, they strictly improve documentation quality.
> [EXTERNAL]: docs(`typing-in-progress`): refine audit file

- subjects/ascii-art-web/README.md
> Before starting, please choose the relevant pull request **Labels**, **Reviewers**, and **Assignees** </br>
> Here are a couple of example tiles of a good pull request:
> - `CON-1234 Title of The Feature or Fix`
> - `[EXTERNAL] Title of The Feature or Fix`
[EXTERNAL] fixed grammar and clarity
> While doing ascii-art-web i encountered some issues regarding the some of the phrasing and information given
> I cleared up some ambiguity and fixed some grammar
> Not many details to be given
> Please assign the label `📦 build` If you want to re-build the following test images:
>- `💻 Sh` 
>- `🚀 JS`
>- `🧩 DOM`
> [EXTERNAL] clarified phrasing and fixed grammar

- subjects/java/raids/jraffic/README.md
- subjects/java/raids/jraffic/audit/README.md
- subjects/road_intersection/README.md
- subjects/road_intersection/audit/README.md
> CON-3610-Fix-Ambiguities-in-road_intersection-Jraffic-Raid

- subjects/brain_fuck/README.md
- subjects/check_user_name/README.md
- subjects/check_user_name/main.rs
- subjects/drop_the_blog/README.md
- subjects/flat_tree/README.md
- subjects/flat_tree/main.rs
- subjects/insertion_sort/README.md
- subjects/insertion_sort/main.rs
- subjects/inv_pyramid/README.md
- subjects/inv_pyramid/main.rs
- subjects/nextprime/README.md
- subjects/order_books/README.md
- subjects/order_books/main.rs
- subjects/organize_garage/README.md
- subjects/own_and_return/README.md
- subjects/own_and_return/main.rs
- subjects/prime_checker/README.md
- subjects/queens/README.md
- subjects/queens/main.rs
- subjects/rpn/README.md
- subjects/scytale_decoder/README.md
- subjects/scytale_decoder/main.rs
[CON-3667](https://01talent.atlassian.net/browse/CON-3667)
[CON-3667]: https://01talent.atlassian.net/browse/CON-3667?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3667 Review All Rust Checkpoints Exercises

- subjects/border_cross/README.md
- subjects/delete_prefix/README.md
- subjects/events/README.md
- subjects/lifetimes/README.md
- subjects/macro_map/README.md
- subjects/matrix/README.md
- subjects/matrix_ops/README.md
[CON-3676](https://01talent.atlassian.net/browse/CON-3676)
[CON-3676]: https://01talent.atlassian.net/browse/CON-3676?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> CON-3676 Fix `quest-09`

- subjects/ai/classification/README.md
> [EXTERNAL] docs (classification): fix and update resource links in documentation

- subjects/ai/emotions-detector/README.md
> [EXTERNAL] docs (emotions-detector): fix and update resource links in documentation

- subjects/ai/nlp-spacy/README.md
> [EXTERNAL] docs (nlp-spicy): fix and update resource links in documentation
